### ISSUE TITLE
[Bug]: fooocus raising exception when load kolors checkpoint model 

### ISSUE THREAD

**Issue by dingwenxia1989** [lllyasviel/Fooocus#3473] opened 2024-08-08 14:33 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

[Bug]: fooocus raising exception when load kolors checkpoint model 
![11](https://github.com/user-attachments/assets/934a6637-7695-47c4-92a4-244b2d3d2c9f)

### Steps to reproduce the problem

![11](https://github.com/user-attachments/assets/c850f417-5d08-4a29-a2d3-b24291c82de9)

### What should have happened?

Kolors is a large-scale text-to-image generation model based on latent diffusion, developed by the Kuaishou Kolors team. Trained on billions of text-image pairs, Kolors model   is compatible for text rendering for both Chinese and English characters. Furthermore, Kolors supports both Chinese and English inputs, demonstrating strong performance in understanding and generating Chinese-specific content.  I hope that fooocus is compatible with the kolors model

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
[Fooocus Model Management] Moving model(s) has taken 0.72 seconds
[Parameters] Adaptive CFG = 7
[Parameters] CLIP Skip = 2
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] Seed = 7188856448608804817
[Parameters] CFG = 3
[Fooocus] Loading control models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Traceback (most recent call last):
  File "F:\Fooocus\Fooocus\modules\async_worker.py", line 1469, in worker
    handler(task)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\Fooocus\modules\async_worker.py", line 1160, in handler
    tasks, use_expansion, loras, current_progress = process_prompt(async_task, async_task.prompt, async_task.negative_prompt,
  File "F:\Fooocus\Fooocus\modules\async_worker.py", line 661, in process_prompt
    pipeline.refresh_everything(refiner_model_name=async_task.refiner_model_name,
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\Fooocus\modules\default_pipeline.py", line 250, in refresh_everything
    refresh_base_model(base_model_name, vae_name)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\Fooocus\modules\default_pipeline.py", line 74, in refresh_base_model
    model_base = core.load_model(filename, vae_filename)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\Fooocus\Fooocus\modules\core.py", line 147, in load_model
    unet, clip, vae, vae_filename, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings,
  File "F:\Fooocus\Fooocus\ldm_patched\modules\sd.py", line 449, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "F:\Fooocus\Fooocus\ldm_patched\modules\model_detection.py", line 163, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "F:\Fooocus\Fooocus\ldm_patched\modules\model_detection.py", line 49, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
Total time: 13.74 seconds
```

### Additional information

fooocus is running on windows 10 with RTX 3090 GPU

**Comment by mashb1t** [comment] 2024-08-08 21:38
Duplicate of https://github.com/lllyasviel/Fooocus/issues/3248, see reasoning in https://github.com/lllyasviel/Fooocus/issues/3248#issuecomment-2213298584 and https://github.com/lllyasviel/Fooocus/discussions/3366#discussioncomment-10161200

**Closed by mashb1t** 2024-08-08 21:38 UTC
Labels: bug, triage
