### ISSUE TITLE
adetailer please

### ISSUE THREAD

**Issue by 2blackbar** [lllyasviel/Fooocus#2118] opened 2024-01-31 21:45 UTC
It changes a lot and would be nice to see it here in this gui

**Comment by mashb1t** [comment] 2024-01-31 22:22
@2blackbar closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/816, find the statement in https://github.com/lllyasviel/Fooocus/issues/816#issuecomment-1788343551

**Closed** 2024-01-31 22:22 UTC
