### ISSUE TITLE
Can the preset be modified to switch in the project instead of the pass startup parameters?

### ISSUE THREAD

**Issue by shawnwu2022** [lllyasviel/Fooocus#767] opened 2023-10-23 01:46 UTC
Can the preset be modified to switch in the project instead of the pass startup parameters?

**Comment by mashb1t** [comment] 2023-12-31 15:18
I've implemented this feature last week, see https://github.com/lllyasviel/Fooocus/pull/1570.
Closing this issue as duplicate of https://github.com/lllyasviel/Fooocus/issues/1058

**Closed by mashb1t** 2023-12-31 15:18 UTC
