### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by jasoncharles** [lllyasviel/Fooocus#100] opened 2023-08-15 08:17 UTC
Hi, 
First, thanks for this project; it is excellent.

I have installed the project as described for a Windows 11 computer. Run the run.bat and generate my first image.

I can see the image being generated in the WebGUI, but then I get a "Connection Error", and the word error appears on the WebGUI.
At the same time, I get the following errors in the CMD box:-

<img width="860" alt="image" src="https://github.com/lllyasviel/Fooocus/assets/29693964/2f51397c-83d8-4829-8a95-457ab5d7d2b6">

When I refresh the web browser, the errors disappear. Then I can generate any images after this successfully, although I no longer see the preview image or the successfully generated images in the WebGUI.

This happens whenever I start the software and generate the first image on the Edge or Brave browsers. 

Thanks

**Comment by mashb1t** [comment] 2024-01-01 20:30
Duplicate of https://github.com/lllyasviel/Fooocus/issues/103

**Closed by mashb1t** 2024-01-01 20:30 UTC
Labels: duplicate
