### ISSUE TITLE
Fooocus image generation is way worse than on versions from 4-5 months ago

### ISSUE THREAD

**Issue by Kingbadger3d** [lllyasviel/Fooocus#2734] opened 2024-04-08 19:45 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Ive not used Fooocus for a while, here's some screen grabs with the settings from 4-5 months back:

![1](https://github.com/lllyasviel/Fooocus/assets/7012139/e2c131c3-ecd3-47b5-8427-a2c2b4d750ee)
![2](https://github.com/lllyasviel/Fooocus/assets/7012139/97d75bdc-79cc-44d8-a3be-c2489deac659)
![3](https://github.com/lllyasviel/Fooocus/assets/7012139/3b9d8b48-af0c-482f-b3ee-d2fadfd26ac9)

Here's the rubbish you get now with latest version with same settings and models (I've tried default ones and looks even worse):

![4](https://github.com/lllyasviel/Fooocus/assets/7012139/2e802f94-47aa-4f1b-be82-983e6144e07b)
![5](https://github.com/lllyasviel/Fooocus/assets/7012139/059edb6c-74ec-4068-b3b2-23486d0d4717)
![6](https://github.com/lllyasviel/Fooocus/assets/7012139/2e2dfee4-223e-4dd1-8e99-5324a34d8f72)
![7](https://github.com/lllyasviel/Fooocus/assets/7012139/500f043f-91cd-4da4-8d03-b63ecffab990)

What have you done?, This tool was great, now its Garbage.

And you've removed downloads of past versions, Good Job!.

Another open source tools that was good bites the dust, very disappointing.

### Steps to reproduce the problem

Run your broken tool

### What should have happened?

An image should of been created that doesnt look like SDL 1.5 at its worst

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
None
```

**Comment by mashb1t** [comment] 2024-04-08 21:45
Thank you for your feedback.

Which model(s) are you using to create the new images? Please post images with metadata or the entry from the history log here for further analysis.

Please also be aware of the fact that comparison between versions of Fooocus should be conducted with the same models, as this ensures a minimisation of external non-Fooocus related parameters.

You can always download older versions by following the official instructions here: https://github.com/lllyasviel/Fooocus/discussions/1405

**Comment by mashb1t** [comment] 2024-04-08 21:51
One more addition: the old images were generated in resolution 1152x852, the new ones in 3475x1991, while also having a different aspect ratio, which does not allow for proper comparison. Be advised that everything outside of Fooocus standard resolutions will result in degrading image quality, see https://github.com/lllyasviel/Fooocus/pull/1617.

**Comment by Kingbadger3d** [comment] 2024-04-09 04:35
Hey Mashb1t, Sorry, but I've been seeing this happen a lot recently with open source tools. I used the same models, same settings, same res. Hahaha, No man I wasn't trying to use 3475x1991 for generation, The new versions of the HTML doc generated that lists settings and the image (which was a genius change at the time no one was doing that) is layed out different to the screen grabs from the old HTML overview file, I took the shots with snipping tool, my screen res is 4k, I zoomed the images in the browser with control +, the res you see is not the render res. You just couldn't see without zooming the image how bad they were.

**Comment by andynormancx** [comment] 2024-04-09 14:22
Are you using the same seeds as the original images ?

If I use your original 253332050 seed, attempt to match the settings as best I can, then I can get very close to your composition. But only if I add "closeup" to the prompt.

You can't match settings exactly as things around the styles have changed over time and unfortunately the HTML log had a lot less detail when you created these images 7 months ago.

However the detail of  image _is_ very different to the your original ones. Mainly it is has mangled faces and hands:

![image](https://github.com/lllyasviel/Fooocus/assets/850121/d337b37c-e872-4bda-9f96-42bac47e62bd)

This is the metadata from that image:

`{
"prompt": "People having a meeting in office building smart meeting, closeup",
"negative_prompt": "text",
"prompt_expansion": "",
"styles": "['Cinematic Diva']",
"performance": "Quality",
"resolution": "(1152, 832)",
"guidance_scale": 3,
"sharpness": 2,
"adm_guidance": "(1.5, 0.8, 0.3)",
"base_model": "talmendoxlSDXL_v11Beta.safetensors",
"refiner_model": "sd_xl_base_1.0.safetensors",
"refiner_switch": 0.5,
"sampler": "dpmpp_2m_sde_gpu",
"scheduler": "karras",
"seed": "253332050",
"lora_combined_1": "sd_xl_offset_example-lora_1.0.safetensors : 0.5",
"metadata_scheme": "fooocus",
"version": "Fooocus v2.3.1"
}`

I tried tweaking various things (including removing the LoRA and the refiner), but the faces always seem to be pretty bad.

If I just use the default realistic preset, change the resolution to 1152*832, pick a cinematic style, I get generally similar quality results to your original.

Here are a couple of examples, possibly not as cinematic as yours, but also far less feature mangling.

![image](https://github.com/lllyasviel/Fooocus/assets/850121/69ebeda3-b10e-48b6-99d4-801756653d5d)
![image](https://github.com/lllyasviel/Fooocus/assets/850121/9b03e118-2fe2-44d6-af83-eba67023f1ff)

And the metadata for the second one.

`{
"prompt": "People having a meeting in office building smart meeting, (closeup)",
"negative_prompt": "unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label",
"prompt_expansion": "People having a meeting in office building smart meeting, (closeup), futuristic, elegant, highly detailed, focus, cinematic, dramatic light, directed, burning, novel, fine detail, clear, very handsome, attractive, strong, epic, stunning, great, artistic, perfect, awesome, intricate, brilliant, singular, best, sharp, determined, passionate, cool, creative",
"styles": "['Fooocus Cinematic', 'Fooocus Negative', 'Fooocus V2']",
"performance": "Quality",
"resolution": "(1152, 832)",
"guidance_scale": 3,
"sharpness": 2,
"adm_guidance": "(1.5, 0.8, 0.3)",
"base_model": "realisticStockPhoto_v20.safetensors",
"refiner_model": "None",
"refiner_switch": 0.5,
"sampler": "dpmpp_2m_sde_gpu",
"scheduler": "karras",
"seed": "253332048",
"metadata_scheme": false,
"version": "Fooocus v2.3.1"
}`

(the way, you can paste the JSON into the prompt to load in the same settings)

Switching over to the model you are using results in a bit of a quality drop off:

![image](https://github.com/lllyasviel/Fooocus/assets/850121/557f93be-927d-48b4-89a9-6f60bb09491c)

(though that is the worst of the images I got with it).

It seems there is something about that model you're using that does not get on very well with the current Fooocus rendering pipeline when it comes to faces and hands.

P.S. to get to see the full size image just click on the image in the HTML log file, it will open in its own window

**Comment by AgentHitmanFaris** [comment] 2024-04-10 08:25
I currently change to comfyui which like change from produa to hyundai

**Comment by mashb1t** [comment] 2024-04-13 11:17
Can't reproduce, closing this issue.

**Closed by mashb1t** 2024-04-13 11:17 UTC
Labels: bug, can't reproduce, feedback pending
