### ISSUE TITLE
There is a visual result issue in V 2.1.66

### ISSUE THREAD

**Issue by kubilaykilinc** [lllyasviel/Fooocus#684] opened 2023-10-14 18:42 UTC
I run Fooocus with standard run.bat. When I use an SD1.5 model as a refiner, these types of textures occur.
I'm using standard settings. When I use an SD1.5 refiner as a refiner, textures begin to appear in the image and deformation occurs.

I run Fooocus with standard run.bat. When I use an SD1.5 model as a refiner, these types of textures occur.

I used the SDXL base 1.0 model as the base model. I used RealisticVision5.1 as Refiner.
As for Style, only Fooocusv2 was active. No other styles were active.

This problem did not exist before 2.1.66.
![image](https://github.com/lllyasviel/Fooocus/assets/18080130/26740e07-8cd5-4c23-b170-f3abb73e5783)
![image](https://github.com/lllyasviel/Fooocus/assets/18080130/7ff99c31-2e69-489e-8517-5d22da53b158)
![image](https://github.com/lllyasviel/Fooocus/assets/18080130/46f07273-dbcc-4cb6-a739-40671fdd7352)

**Comment by lllyasviel** [comment] 2023-10-14 19:03
give prompt seed and model name

**Comment by kubilaykilinc** [comment] 2023-10-14 20:24
My Hardware :
Windows 11 - 32 GB Ram - AMD Ryzen 5 5600G with Radeon Graphics - NVIDA RTX 3060 12GB (Latest Driver 537.58) - 1 TB SSD

Fooocus Version 2.1.66
Running - run_realistic.bat

Base SDXL model: realisticStockPhoto_v10.safetensors
Refier model : (SD 1.5 model) realisticVisionV51_v51VAE.safetensors

LORA 1 : SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors

**Comment by kubilaykilinc** [comment] 2023-10-14 20:28
My Hardware :
Windows 11 - 32 GB Ram - AMD Ryzen 5 5600G with Radeon Graphics - NVIDA RTX 3060 12GB (Latest Driver 537.58) - 1 TB SSD

Fooocus Version 2.1.66
Running - run_realistic.bat

Base SDXL model: realisticStockPhoto_v10.safetensors
Refier model : (SD 1.5 model) realisticVisionV51_v51VAE.safetensors

LORA 1 : SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors
LORA 1 weight : 0.25

Positive Prompt
a vintage style Olive oil product  in a vintage style room

Negative Prompt (Standart Fooocus prompt)
unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label

Seed : 0

Other settings are standard fooocus settings (style, cfg level, developer debug mode etc.(
FreeU mode : disable

and result

![image](https://github.com/lllyasviel/Fooocus/assets/18080130/de915dea-bd8d-45c8-b8cd-db69d8079eb4)

I tried this setup with another SD.1.5 model as refiner. I am getting same issue.

**Comment by kubilaykilinc** [comment] 2023-10-14 21:26
All the setup I mentioned above is the same.
seeds 0
prompt an apple

A.
Base SDXL model: realisticStockPhoto_v10.safetensors
Refiner model: (SD 1.5 model) realisticVisionV51_v51VAE.safetensors
![2023-10-14_23-58-16_7890](https://github.com/lllyasviel/Fooocus/assets/18080130/bd03d354-4504-4eb3-b4c5-d203c8d7ab00)

B.
Base SDXL model: realisticStockPhoto_v10.safetensors
Refiner model: (SDXL model) sd_xl_refiner_1.0_0.9vae.safetensors
![2023-10-15_00-03-52_7890](https://github.com/lllyasviel/Fooocus/assets/18080130/3b0cf12f-3303-4af8-b57a-f6c8f2ed9f09)

I use SD 1.5 refiners for better photorealistic results.
When I use any SDXL model as a refiner. No problem. However, if the refiner is SD1.5 model. There is this problem.

**Comment by lllyasviel** [comment] 2023-10-14 22:06
thanks will take a look soon

**Comment by lllyasviel** [comment] 2023-10-14 23:07
This is the default result
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/934ddc2b-2c9a-4352-8487-d65e0598e532)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/9e2b31f5-fabc-4b07-adef-59de7f36579a)
If you use another sd1.5 as refiner, result will be a bit worse
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/563f3444-8747-44f6-b192-1af6a30b2d7b)
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/0ab32127-0105-49d5-b34e-bbff0cb2dc7f)

But I cannot reproduce your examples.

The solution is to just fo not use 1.5  refiner for realistic XL. The 1.5 refiner only make things better for anime images in most cases. 

Previous  2.1.60 has same problem but less obvious. Since this 1.5 refiner is mostly for anime, the implementation will mainly target improving anime images. This problem does not exist in anime images.

**Comment by lllyasviel** [comment] 2023-10-14 23:12
but i will take a look again since this is very strange

**Comment by lllyasviel** [comment] 2023-10-15 03:08
see if fixed in 2.1.67

**Closed** 2023-10-15 03:15 UTC
