### ISSUE TITLE
[Bug]: app-1  | sh: 1: /content/entrypoint.sh: not found (docker compose)

### ISSUE THREAD

**Issue by greatcat19** [lllyasviel/Fooocus#2863] opened 2024-05-03 20:29 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

```

docker compose build --no-cache


(venv) deb-workshop :: ~/Fooocus-2024 ‹main› » docker-compose up
WARN[0000] /home/username/Fooocus-2024/docker-compose.yml: `version` is obsolete
[+] Running 2/3
 ✔ Network fooocus-2024_default        Created                                                           0.1s
 ✔ Volume "fooocus-2024_fooocus-data"  Created                                                           0.0s
 ⠋ Container fooocus-2024-app-1        Created                                                           0.1s
Attaching to app-1
app-1  | sh: 1: /content/entrypoint.sh: not found
app-1 exited with code 127
```

### Steps to reproduce the problem

latest main branch

### What should have happened?

it can run

### Where are you running Fooocus?

None

### Console logs

```Shell
docker compose build --no-cache


(venv) deb-workshop :: ~/Fooocus-2024 ‹main› » docker-compose up
WARN[0000] /home/username/Fooocus-2024/docker-compose.yml: `version` is obsolete
[+] Running 2/3
 ✔ Network fooocus-2024_default        Created                                                           0.1s
 ✔ Volume "fooocus-2024_fooocus-data"  Created                                                           0.0s
 ⠋ Container fooocus-2024-app-1        Created                                                           0.1s
Attaching to app-1
app-1  | sh: 1: /content/entrypoint.sh: not found
app-1 exited with code 127
```
```


### Additional information

_No response_

**Comment by mashb1t** [comment] 2024-05-04 05:48
Duplicate of https://github.com/lllyasviel/Fooocus/discussions/2836, already fixed in https://github.com/lllyasviel/Fooocus/pull/2843, but i'll double-check.
Solution in https://github.com/lllyasviel/Fooocus/discussions/2836#discussioncomment-9293008

**Closed** 2024-05-04 12:37 UTC
Labels: bug

**Comment by mashb1t** [comment] 2024-05-04 12:39
Reverted previous changes, as they were a false alarm. Works now OOTB once again when not tampering with encoding of line breaks (entrypoint.sh has to be LF as it is now).
