### ISSUE TITLE
[Feature Request]: Option to place image from clipboard

### ISSUE THREAD

**Issue by thekingbalXD** [lllyasviel/Fooocus#2565] opened 2024-03-19 07:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

On mobile it would be an easier method since you can't drag and drop the picture.

### Proposed workflow

1. Copy the picture from the internet
2. You press the button to place it in the Image promt, inpaint, ect.

**Comment by mashb1t** [comment] 2024-03-19 17:37
Gradio 3.41.2 has no such functionality, at least not by default. What you can already do is to download an image and then insert it again.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1012

**Closed by mashb1t** 2024-03-19 17:37 UTC
Labels: enhancement, triage
