### ISSUE TITLE
Please allow fooocus to import images from the clipboard with ctrl+v

### ISSUE THREAD

**Issue by pixelnotehello** [lllyasviel/Fooocus#943] opened 2023-11-14 00:50 UTC
This function is to use the screenshot key or ctrl+c to move the image to the clipboard, and import it on the Focus page with ctrl+v,
I use this feature very very extensively in other webuis, and I cannot do without it. 
I hope author can add it in Focus too. Thank you very much!!

**Comment by stubkan** [comment] 2023-11-14 18:27
+1 for this.  ctrl+v would be very handy, especially when you are working with images in other programs or browser tabs.

At the moment, the workaround is that you can drag image from a different browser tab and then drop it in your image window, this does work.

But drag drop is risky, since if you drag to the wrong place it will erase the whole window.

**Comment by RodTDai** [comment] 2023-11-14 19:42
+1

**Comment by mashb1t** [comment] 2023-11-26 12:12
potential solution in https://github.com/lllyasviel/Fooocus/issues/1012

**Comment by mashb1t** [comment] 2023-12-31 00:41
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1012

**Closed by mashb1t** 2023-12-31 00:41 UTC
