### ISSUE TITLE
Soft Inpainting

### ISSUE THREAD

**Issue by CognitiveDiffusion** [lllyasviel/Fooocus#2363] opened 2024-02-26 19:07 UTC
Hi Illyasviel,

Thanks for all your work.

Please consider adding "Soft Inpainting" to your automatic and other ways of inpainting. From what I understand, it makes a huge difference:

https://www.reddit.com/r/StableDiffusion/comments/1ankbwe/a1111_dev_a1111_forge_have_a_new_feature_called/

**Comment by mashb1t** [comment] 2024-02-26 23:49
Hey @CognitiveDiffusion, thanks for the link.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1788, but posting the link there. Feel free to head over and continue the discussion.

**Closed by mashb1t** 2024-02-26 23:49 UTC

**Comment by artem-istranin** [comment] 2024-07-10 15:04
Hey @mashb1t ! May I ask if there is some update regarding soft inpainting to be implemented in fooocus? I see in all related issues reference to some other related issue, but no really answer regarding if you are going to add soft inpainting or not. Would be great to know if this is something you consider to implement?

**Comment by mashb1t** [comment] 2024-07-10 15:50
@artem-istranin see https://github.com/lllyasviel/Fooocus/issues/2407#issuecomment-2171919686, waiting for help on this PR.
