### ISSUE TITLE
[Feature Request]:  Please add support for FLUX.1-dev 

### ISSUE THREAD

**Issue by elyzionz** [lllyasviel/Fooocus#3442] opened 2024-08-03 21:12 UTC
Please add support for the new generation FLUX.1-dev image model

**Comment by mashb1t** [comment] 2024-08-03 21:47
Duplicate of https://github.com/lllyasviel/Fooocus/issues/3424, also see https://github.com/lllyasviel/Fooocus/discussions/3440

**Closed by mashb1t** 2024-08-03 21:47 UTC
Labels: enhancement, triage
