### ISSUE TITLE
[Feature Request]: and for me its a BUG "every time i press any kind of preset all is gone"

### ISSUE THREAD

**Issue by kalle07** [lllyasviel/Fooocus#2749] opened 2024-04-11 12:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

save my preset!!!

### Proposed workflow

buttun "save preset"

### Additional information

ill explain

every time i press any kind of preset all is gone
(negprompt and loras)

ok i can start with an own config.txt  but anyway if i change a litle negprompt and choose 3 loras 
now try another preset 
BAAAAm
all is gone negprompt gone, loras gone
if i reuse the last preset all is like in the start but lose my changes in negprompt and loras ...

what is your idea behind that ?
allways should be all saved temporaly on activated preset, is that not much better ?  ;)

**Comment by mashb1t** [comment] 2024-04-13 11:13
This is the purpose of a preset, it loads the preset options.
Feel free to implement a "save preset" button and provide a PR, i sadly currently do not have the time to do so.

**Comment by mashb1t** [comment] 2024-04-13 11:14
Potential duplicate of https://github.com/lllyasviel/Fooocus/issues/1622

**Comment by kalle07** [comment] 2024-04-13 11:46
no problem ... its all free so what i ask for  ;)

**Closed** 2024-05-19 06:35 UTC
Labels: enhancement
