### ISSUE TITLE
[Bug]: cv2 and dll errors

### ISSUE THREAD

**Issue by anonymouso5310** [lllyasviel/Fooocus#2840] opened 2024-04-30 17:19 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I have downloaded fooocus and when im launching run.bat or the others .bat i got errors

### Steps to reproduce the problem

1. donwload 2.extract 3. run it

### What should have happened?

.

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
C:\Users\Desktop\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
Traceback (most recent call last):
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\Fooocus\launch.py", line 83, in <module>
    from modules import config
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\config.py", line 8, in <module>
    import modules.sdxl_styles
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\sdxl_styles.py", line 7, in <module>
    from modules.util import get_files_from_folder
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\util.py", line 8, in <module>
    import cv2
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 126, in import_module
    if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
ImportError: DLL load failed while importing cv2: Le module spécifié est introuvable.

C:\Users\Desktop\Fooocus_win64_2-1-831>pause
Appuyez sur une touche pour continuer...
```

**Comment by mashb1t** [comment] 2024-04-30 22:12
Duplicate of https://github.com/lllyasviel/Fooocus/issues/2062.
Make sure you've used 7zip to extract the zip file as well as your Antivirus software hasn't blocked/deleted/quarantined files.

**Closed by mashb1t** 2024-04-30 22:12 UTC
Labels: bug, triage
