### ISSUE TITLE
Combine ImagePrompt and FaceSwap crash Fooocus

### ISSUE THREAD

**Issue by JulienFiant** [lllyasviel/Fooocus#1844] opened 2024-01-09 22:30 UTC
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

Hello All

I have an issue, i'm on Fooocus 2.1.862 working on a colab
When i tried to do an generation with an input imageprompt + an input faceswap, Fooocus stop to work with a Ctrl+C exit "^C"
I don't use any args with the python launcher and i tried with "Speed", "Quality" and "Extreme Speed", same result for all

Log :
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ('sdxl_lcm_lora.safetensors', 1.0)] for model [/content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Loaded LoRA [/content/Fooocus/models/loras/sdxl_lcm_lora.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 1.0.
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 2.19 seconds
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.12 seconds
[Fooocus] Image processing ...
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
^C

Thanks you for your help

**Comment by mashb1t** [comment] 2024-01-09 22:48
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1709, https://github.com/lllyasviel/Fooocus/issues/1574, etc.
Please check if https://github.com/lllyasviel/Fooocus/pull/1710 works for you.

**Closed by mashb1t** 2024-01-09 22:48 UTC
