### ISSUE TITLE
[Feature Request]: stable video diffusion

### ISSUE THREAD

**Issue by bamtheboozle** [lllyasviel/Fooocus#2706] opened 2024-04-04 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

is it possible to integrate stable video diffusion into fooocus?

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment] 2024-04-04 20:19
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1031, also see https://github.com/lllyasviel/Fooocus/discussions/390#discussioncomment-9011639

**Closed by mashb1t** 2024-04-04 20:19 UTC
Labels: enhancement, triage
