### ISSUE TITLE
Changing the drive of the output folder breaks the History Log link

### ISSUE THREAD

**Issue by midareashi** [lllyasviel/Fooocus#2371] opened 2024-02-27 15:47 UTC
[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
I changed the path_outputs to a different drive (fooocus is installed on D and output saves on G) and the History Log link errors with `"detail": "File not allowed: G:/SD/Outputs/Fooocus/2024-02-27/log.html."`

The url appears like this `127.0.0.1:7865/file=G:/SD/Outputs/Fooocus/2024-02-27/log.html` and has to be changed to this `file:///G:/SD/Outputs/Fooocus/2024-02-27/log.html` to work

**Comment by mashb1t** [comment] 2024-02-27 23:42
Already fixed in https://github.com/lllyasviel/Fooocus/pull/2332, closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/907.
Please check out the develop branch, whee the change has already been included.

**Closed by mashb1t** 2024-02-27 23:42 UTC
