### ISSUE TITLE
SD1.5 models as base model

### ISSUE THREAD

**Issue by xunkar** [lllyasviel/Fooocus#2400] opened 2024-03-01 10:27 UTC
Everythin is in the title I guess. Since SD1.5 models can be used as refiners, could it be possible to include the option of using them as base models too? As you know many LORAs are based on 1.5 which would open a lot of possibilities. Probably this would also require making a few mode resolutions availabe (around 768x512)

**Comment by mashb1t** [comment] 2024-03-01 17:27
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2104

**Closed by mashb1t** 2024-03-01 17:27 UTC
