### ISSUE TITLE
[Bug]: some parameters in "config.txt" ignored on Fooocus startup in V2.3.0

### ISSUE THREAD

**Issue by cuffins** [lllyasviel/Fooocus#2566] opened 2024-03-19 08:43 UTC
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Fooocus is ignoring some entries in "config.txt"

### Steps to reproduce the problem

- Modify the  default checkpoit and /or default LoRa in"config.txt" file 
- Fooocus will come up with default settings for checkpoint and LoRA ignoring the changes

### What should have happened?

change all the settings stated  in "config.txt"

### What browsers do you use to access Fooocus?

Google Chrome, Brave, Microsoft Edge

### Where are you running Fooocus?

Locally

### Console logs

```Shell
none
```

**Comment by cuffins** [comment] 2024-03-19 08:52
It seems there is a new config-structure in V2.3.0. When you have installed Fooocus and updated from an old version, there are missing parameters in the old config-file so Fooocus seems to ignore it. Maybe it will be better to replace the old config.txt with the update.

**Comment by cuffins** [comment] 2024-03-19 09:20
I have replaced the old "config.txt" with the new "config_modification_tutorial.txt" renamed it to "config.txt" deleted the comments in the top and changed the parameter to my preferred ones. Some changes are accepted like Model path and Temp dir, others not like Default checkpoint default loras etc.

**Comment by LuosVleer** [comment] 2024-03-19 09:51
can confirm,

I spent an hour trying to figure out what was going on, then checked the issue tracker.
I hope it's fixed soon! good luck!

**Comment by cuffins** [comment] 2024-03-19 10:06
yes, after spending a lot of time I can confirm.

**Comment by mashb1t** [comment] 2024-03-19 17:34
Can you please provide the terminal output when the config couldn't be imported? This helps in narrowing down the issue. THanks!

**Comment by LuosVleer** [comment] 2024-03-19 18:53
Hope I'm doing this right, as I am not used to this kind of thing, I'm better suited at making vfx for games XD
else, we might want to wait for Cuffins.

This is just converting the config_modification_tutorial to config.txt


`J:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Fast-forward merge
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.0
Failed to load config file "J:\Fooocus\Fooocus\config.txt" . The reason is: Expecting value: line 1 column 1 (char 0)
Please make sure that:
1. The file "J:\Fooocus\Fooocus\config.txt" is a valid text file, and you have access to read it.
2. Use "\\" instead of "\" when describing paths.
3. There is no "," before the last "}".
4. All key/value formats are correct.`

And this was with the config file that worked last night before the update, but resulted in Fooocus not loading at all today:
`Total VRAM 11264 MB, total RAM 65409 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "J:\Fooocus\Fooocus\modules\async_worker.py", line 32, in worker
    import modules.default_pipeline as pipeline
  File "J:\Fooocus\Fooocus\modules\default_pipeline.py", line 257, in <module>
    loras=get_enabled_loras(modules.config.default_loras)
  File "J:\Fooocus\Fooocus\modules\util.py", line 366, in get_enabled_loras
    return [[lora[1], lora[2]] for lora in loras if lora[0]]
  File "J:\Fooocus\Fooocus\modules\util.py", line 366, in <listcomp>
    return [[lora[1], lora[2]] for lora in loras if lora[0]]
IndexError: list index out of range
Traceback (most recent call last):
  File "J:\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "J:\Fooocus\Fooocus\launch.py", line 136, in <module>
    from webui import *
  File "J:\Fooocus\Fooocus\webui.py", line 364, in <module>
    for i, (enabled, filename, weight) in enumerate(modules.config.default_loras):
ValueError: not enough values to unpack (expected 3, got 2)

J:\Fooocus>pause
Press any key to continue . . .`

I attached the config.txt that worked last night, but not with the 2.3 update.

[config.txt](https://github.com/lllyasviel/Fooocus/files/14655060/config.txt)

**Comment by LuosVleer** [comment] 2024-03-19 19:04
Hmm, after some additional inspection:

```
  "default_loras": [
        [
            true,
            "SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors",
            0.25
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ],
        [
            true,
            "None",
            1.0
        ]
    ],
    "default_max_lora_number": 5,
```

If the default max lora number is higher than 5, yet "the default_loras" only has 5 defaults mentioned, it seems fooocus throws a:

```
VAE dtype: torch.float32
Using pytorch cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "J:\Fooocus\Fooocus\modules\async_worker.py", line 32, in worker
    import modules.default_pipeline as pipeline
  File "J:\Fooocus\Fooocus\modules\default_pipeline.py", line 257, in <module>
    loras=get_enabled_loras(modules.config.default_loras)
  File "J:\Fooocus\Fooocus\modules\util.py", line 366, in get_enabled_loras
    return [[lora[1], lora[2]] for lora in loras if lora[0]]
  File "J:\Fooocus\Fooocus\modules\util.py", line 366, in <listcomp>
    return [[lora[1], lora[2]] for lora in loras if lora[0]]
IndexError: list index out of range
Traceback (most recent call last):
  File "J:\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "J:\Fooocus\Fooocus\launch.py", line 136, in <module>
    from webui import *
  File "J:\Fooocus\Fooocus\webui.py", line 364, in <module>
    for i, (enabled, filename, weight) in enumerate(modules.config.default_loras):
ValueError: not enough values to unpack (expected 3, got 2)
```

also, --for me-- it fully ignores
```
    "default_cfg_scale": 3.14,
    "default_sample_sharpness": 2.25,
    "default_model": "talesOfDigitalDesire_v10.safetensors"
```
regardless.

Hope that helps at least a little.

**Comment by DavidDragonsage** [comment] 2024-03-19 20:06
I am experiencing similar problems with Fooocus 2.3. Please see the attached zip for the console log, config.txt, default.json, and four screen captures.

The use of presets seems to improperly wipe out the config.txt settings - once a new preset is selected then the errors occur.

When Fooocus starts it uses the "initial" preset. As you can see in "Initial Image Number Correct.png" screen capture, the Image Number is set to "5", the value I set in config.txt (the value would normally be set to "2").

Also, on the Model tab, "Initial LoRAs Correct.png", LoRA 1 is correctly set to "sd_xl_offset_example-lora_1.0.safetensors", Weight = 0.1. LoRA 2 is disabled, as I specified in config.txt.

Now, if I switch to the "default" preset (or any other preset), the Image Number is now set to "1", as shown in "Image Number Incorrect.png". There is no Image Number setting in default.json, so I tried adding the Image Number parameter to the default.json as an experiment, but it did not help.

All the LoRA settings for the default preset (or any other preset) are now absent, as shown in "No Default LoRAs.png". There are no LoRAs, the Weights are all set to 1, and all the LoRAs are now enabled. The default preset specifies "sd_xl_offset_example-lora_1.0.safetensors", Weight = 0.1, but those values have been removed.

However, if I remove "True" from all the LoRA settings for a particular preset, then that preset will display the correct values. Except that all LoRAs are now enabled, contrary to my config.txt settings (LoRA 2 should be disabled).

Please don't hesitate to ask if you need further details.

[Fooocus 2.3 Bug Report.zip](https://github.com/lllyasviel/Fooocus/files/14655646/Fooocus.2.3.Bug.Report.zip)

**Comment by TheNextLevel** [comment] 2024-03-19 20:25
Phuuu I was on the verge of freaking out that my default_prompt, default_aspect_ratio and default_styles setting were being ignored. Thank goodness I checked the issue tracker....

**Comment by DavidDragonsage** [comment] 2024-03-19 20:30
Ironically, if you use your own custom presets, they will all work correctly (as long as you don't try to specify whether a LoRA is on or off  - true or false - in you custom preset).

**Comment by Tra2x** [comment] 2024-03-19 21:54
Another thing which isn't working anymore, set default styles to nothing, to not mark any style when start looous.
`"default_styles": [],` worked fine in the config.txt till the update

**Comment by mashb1t** [comment] 2024-03-19 22:11
@LuosVleer default_max_lora_number issue fixed in https://github.com/lllyasviel/Fooocus/pull/2576

**Comment by mashb1t** [comment] 2024-03-19 22:14
@skylerblack2 you were just 2 minuts too late ^^
@cuffins @DavidDragonsage please check again with the latest version, jsut please reopen Fooocus and check if it's now working.

**Comment by DavidDragonsage** [comment] 2024-03-19 22:49
I can see that Fooocus did an update because of file times on the presets, but no change on these faults:

1) the Image Number is still set to 1 for all presets, including my custom ones
2) the LoRA settings for the Fooocus presets are still trashed as they were before
3) the LoRA settings for my custom presets are not trashed. This is because I do not have the True/False values in mine. If I edit the Fooocus supplied presets to not have the LoRA True/False values then the LoRA values display correctly
4) the disable (False) settings for LoRA 2 and LoRA 3 that I have set in config.txt are ignored. All LoRAs are enabled for both Fooocus supplied and custom presets

So for me, no change in the faults I had detected earlier.

**Comment by mashb1t** [comment] 2024-03-19 22:51
@DavidDragonsage will check again tomorrow

**Comment by DavidDragonsage** [comment] 2024-03-19 22:59
Of course - time for a break. Thank you for looking at this right away.

**Comment by LuosVleer** [comment] 2024-03-19 23:09
> @LuosVleer default_max_lora_number issue fixed in #2576

thanks! I'll check it out tomorrow! Have a well-deserved sleep!

**Comment by Sirmadsen** [comment] 2024-03-19 23:49
Removing checkpoint download and lora download don't work. It still downloads the default checkpoint and lora. The checkpoint being downloaded is also out of date (not the problem). I'm on a very slow connection and don't use the default checkpoint at all so downloading a 6GB checkpoint is not ideal.

**Comment by cuffins** [comment] 2024-03-20 09:04
@mashb1t 
After a lot of testing I have noticed the following issues:

The initial profile is not working as expected. Only settings made in the "config.txt" which are not included in the "Default.json"
will take effect. It seems the "Default.json" ist overwriting the settings in the "config.txt".

The "default_model" and "default_refiner" working fine as far as I can tell. 
The LoRA settings will only be loaded at startup (from the "Default.json" if specified there) and get lost when switching between the profiles, even if you choose the Default profile. Reloading the page will bring the LoRA settings (from the "Default.json" if specified there) back.

There is a lot of interfering between the settings going on. I think it would 
be a much cleaner approach to load the initial settings specified in the "config.txt" at
the moment, like the other settings via a .json file in the Profiles folder. Maybe
two buttons "save as profile" and "change profile" in the settings tab would be a good idea. I don't know how 
complex this may be, but in my view grabbing all the choosed settings and writing a .json
to the Profiles folder is worth a look. 

I hope this helps you fixing the issues. 
Thank's a lot for your great work and the effort you put into it!

**Comment by techalexx** [comment] 2024-03-20 11:14
It doesn’t apply from my config:
default_model
loras
default_styles

**Comment by TheNextLevel** [comment] 2024-03-20 15:00
> @skylerblack2 you were just 2 minuts too late ^^ @cuffins @DavidDragonsage @TheNextLevel please check again with the latest version, just please reopen Fooocus and check if it's now working.

Nope. still ignoring

**Comment by mashb1t** [comment] 2024-03-20 20:16
> It seems the "Default.json" ist overwriting the settings in the "config.txt".

This is true, but not intended. This was an issue when solving merge conflicts, where first default.json was loaded, then settings.txt, then default.json again (last one now removed). This should cover the majority of issues reported for config.

default_max_lora_number is only loaded initially as it is also used in image generation and has to be guaranteed no matter which preset / amount of users uses Fooocus.

default_model and default_styles => can't reproduce, works for me
default_loras => fixed, forgot to add LoRA enable to tuple unpacking + added backwards compatibility for old history log. Sorry.

This shoud wrap things up. Did I forget something?
Please check again.

**Closed** 2024-03-20 20:16 UTC
Labels: bug

**Comment by TheNextLevel** [comment] 2024-03-20 21:58
> > @skylerblack2 you were just 2 minuts too late ^^ @cuffins @DavidDragonsage @TheNextLevel please check again with the latest version, just please reopen Fooocus and check if it's now working.
> 
> Nope. still ignoring

Works now. Thanks

**Comment by DavidDragonsage** [comment] 2024-03-20 23:57
I'm happy to report that all the LoRA settings in the presets are working nicely now, including defaulting to True/False (On/Off). That's great!

The only fault remaining for me is that "default_image_number" resets to 1 every time I change presets. My setting in config.txt is
 "default_image_number": 5,

I tried adding "default_image_number": 5, to my custom presets but that did not help.

**Comment by vespersland** [comment] 2024-03-22 14:02
why this version is too slow? i have a rtx 4070 ti ,any suggestions?

**Comment by mashb1t** [comment] 2024-03-22 14:08
@vespersland off-topic and nothing has changed in processing. Feel free to open an issue if there is a problem.
