### ISSUE TITLE
[Bug]: Unable to generate url link

### ISSUE THREAD

**Issue by igninjaz** [lllyasviel/Fooocus#2819] opened 2024-04-27 09:38 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

![Screenshot 2024-04-27 113501](https://github.com/lllyasviel/Fooocus/assets/157118183/efc50aad-f974-4059-ae48-c8a01cf69d2b)

### Steps to reproduce the problem

Google Pro

### What should have happened?

.

### Where are you running Fooocus?

None

### Console logs

```Shell
/
```

**Comment by poor7** [comment] 2024-04-27 12:26
Duplicated 
https://github.com/lllyasviel/Fooocus/issues/2817
https://github.com/lllyasviel/Fooocus/issues/2815

**Comment by KirtiKousik** [comment] 2024-04-27 13:07
It's working now. There was a problem with gradio share api.

**Comment by mashb1t** [comment] 2024-04-27 13:44
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2815

**Closed by mashb1t** 2024-04-27 13:44 UTC
Labels: bug, triage

**Comment by igninjaz** [comment] 2024-04-30 17:03
Same issue. Again.
