### ISSUE TITLE
Inpaint mask invert?

### ISSUE THREAD

**Issue by JohnTesla** [lllyasviel/Fooocus#1662] opened 2023-12-30 05:50 UTC
INVERT of Inpaint MASK
Option - INPAINT NOT MASKED
Is this possible?

**Comment by mashb1t** [comment] 2023-12-30 11:47
This is not yet possible.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1404.

**Closed by mashb1t** 2023-12-30 11:47 UTC
