### ISSUE TITLE
Failed. generation failure with face swap via google colab

### ISSUE THREAD

**Issue by Woukim** [lllyasviel/Fooocus#977] opened 2023-11-18 05:40 UTC
Here are the parameters I changed, +used image prompt ( face swap )
![image](https://github.com/lllyasviel/Fooocus/assets/138323639/798dbffb-f93c-4aa5-9290-a541c0f51acc)

![image](https://github.com/lllyasviel/Fooocus/assets/138323639/3544c85a-9e6f-4328-869b-dd8b6bf5722c)

![image](https://github.com/lllyasviel/Fooocus/assets/138323639/55dfb5f8-7542-4b26-83ef-2883c8ef0bf9)

**Comment by mashb1t** [comment] 2023-12-31 00:02
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1574

**Closed by mashb1t** 2023-12-31 00:02 UTC
