### ISSUE TITLE
TensorRT

### ISSUE THREAD

**Issue by UmutHasanoglu** [lllyasviel/Fooocus#941] opened 2023-11-13 20:43 UTC
I know it's not easy but is there a change that you add TensorRT support for Fooocus?

**Comment by kubilaykilinc** [comment] 2023-11-13 21:57
My opinion, we do not need TensorRT anymore.
after LCM sampling and LCM scheduler

**Comment by RodTDai** [comment] 2023-11-14 19:43
> My opinion, we do not need TensorRT anymore. after LCM sampling and LCM scheduler

yes, we need it. They are different things

**Comment by mashb1t** [comment] 2023-12-31 00:42
Duplicate of https://github.com/lllyasviel/Fooocus/issues/897

**Closed by mashb1t** 2023-12-31 00:42 UTC

**Comment by mashb1t** [comment] 2023-12-31 00:43
> My opinion, we do not need TensorRT anymore. after LCM sampling and LCM scheduler

btw to spice things up there also is SDXL Turbo now (https://github.com/lllyasviel/Fooocus/pull/1580)
