### ISSUE TITLE
[Bug]:      [Errno 60] Operation timed out> on MAC pro

### ISSUE THREAD

**Issue by yuxistar001** [lllyasviel/Fooocus#2518] opened 2024-03-13 02:14 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Loaded preset: /Users/nikiforosliang/Fooocus/presets/realistic.json
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % 

### Steps to reproduce the problem

(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Loaded preset: /Users/nikiforosliang/Fooocus/presets/realistic.json
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % 

### What should have happened?

(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Loaded preset: /Users/nikiforosliang/Fooocus/presets/realistic.json
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % 

### Where are you running Fooocus?

None

### Console logs

```Shell
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus % python entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--preset', 'realistic']
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
Fooocus version: 2.2.1
Loaded preset: /Users/nikiforosliang/Fooocus/presets/realistic.json
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/nikiforosliang/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikiforosliang/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/nikiforosliang/Fooocus/launch.py", line 124, in <module>
    download_models()
  File "/Users/nikiforosliang/Fooocus/launch.py", line 90, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/nikiforosliang/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
(fooocus) nikiforosliang@Nikifoross-MacBook-Pro Fooocus %
```

**Comment by mashb1t** [comment] 2024-03-13 08:59
Make sure you can acces the file https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth. If you can, please try to download it and put it (and renam it if necessary) in the corresponding directory, which you can find in the config.py. Continue in an iterative approach.

If this doesn't work then your network blocks reqursts to the domain and you can check if it works with(out) using a VPN.

**Comment by mashb1t** [comment] 2024-03-13 09:01
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/641

**Closed by mashb1t** 2024-03-13 09:01 UTC
Labels: bug, feedback pending
