### ISSUE TITLE
Stuck on download?

### ISSUE THREAD

**Issue by harrypango** [lllyasviel/Fooocus#1734] opened 2024-01-03 17:19 UTC
Hello! I have been trying to complete the installation but I am stuck here for a while now after the download was complete. It's the second time I download the models and it's stuck for quite some time now. 
![Screenshot_3](https://github.com/lllyasviel/Fooocus/assets/132347928/39718e19-36d6-431c-9ff9-1b22dbd098c9)

I can also see "partial download" on my files:
![Screenshot_4](https://github.com/lllyasviel/Fooocus/assets/132347928/6b492c64-f79a-4e61-a78f-ff62d12fef52)

Is this something related to my machine? I have 16GB RAM and a 1660Ti.

**Comment by mashb1t** [comment] 2024-01-03 19:15
If it's stuck you can also manually try to download the checkpoint and put it in `Fooocus/models/checkpoints`. Please make sure you have enough storage though. 
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1536.

**Comment by harrypango** [comment] 2024-01-03 23:30
> If it's stuck you can also manually try to download the checkpoint and put it in `Fooocus/models/checkpoints`. Please make sure you have enough storage though. Duplicate of #1536.

Ok, this worked perfectly well, thank you! About the storage, I had about 15GB left on my 250GB SSD. When I ran the .bat file and the image was being generated, my storage went to about 1GB left, is this what you meant by "enough storage"? Will storage be allocated like this every time I try to generate a new image?

**Comment by mashb1t** [comment] 2024-01-03 23:48
This has to do with the system swap. Windows uses your disk as temporary storage for data normally being located in RAM as it detects that RAM is getting low.
The swap gile can be static or dynamic, i assume the latter on your system. This is why additional storage is allocated during generation.
No ToDo on your side except maybe some cleanup of your drive to prevent potential storage issues, but if you're interested you can find more information here: https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap

**Closed by mashb1t** 2024-01-03 23:48 UTC
Labels: duplicate

**Comment by harrypango** [comment] 2024-01-04 00:01
> This has to do with the system swap. Windows uses your disk as temporary storage for data normally being located in RAM as it detects that RAM is getting low. The swap gile can be static or dynamic, i assume the latter on your system. This is why additional storage is allocated during generation. No ToDo on your side except maybe some cleanup of your drive to prevent potential storage issues, but if you're interested you can find more information here: https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap

I was able to free up a lot of space and I think I should be good for now. Thanks for the help!
