### ISSUE TITLE
[Feature Request] Batch Prompts

### ISSUE THREAD

**Issue by deadpipe** [lllyasviel/Fooocus#749] opened 2023-10-20 18:14 UTC
Hi,

I highly appreciate you for keeping this Fooocus software open source and available to community. It would be great to have a feature to generate images in batch. I meant submitting list of prompts in textbox or uploading txt file. I think there is a similar feature in automatic1111. Here is a screenshot for reference.

![image](https://github.com/lllyasviel/Fooocus/assets/142412134/b86bb81a-6fe7-4e65-ac0f-51ed9b5b12d6)

You see, there are 4 prompts - each for different image.

**Comment by mashb1t** [comment] 2023-12-31 15:26
This is (more or less) soon possible using PR https://github.com/lllyasviel/Fooocus/pull/1503.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1146

**Closed by mashb1t** 2023-12-31 15:26 UTC
