### ISSUE TITLE
CivitAI model not downloading / model corrupted

### ISSUE THREAD

**Issue by MasterRed0** [lllyasviel/Fooocus#2041] opened 2024-01-25 14:05 UTC
**Read Troubleshoot**
I have read the troubleshoot. It mentions this issue, however my problem isn't solved

**Describe the problem**
Im using Colab Pro. It had been working just fine until today, when I tried to run the code in the Colab notebook like usual, downloading the CivitAI checkpoint at the same time, however today it's different (I haven't changed anything). When normally it would just download the whole thing, it immediately skips downloading it and saves an undownloaded file. I tried running it many times, and on different models as well.
This is what keeps happenening:
![image](https://github.com/lllyasviel/Fooocus/assets/155583984/94e30f43-1191-4012-95b5-70e7d8d4adcd)
Then when I try to use the same checkpoint I get an error in the app and this message in the log:
![image](https://github.com/lllyasviel/Fooocus/assets/155583984/013917b7-8ffb-4206-a01f-80e20e0441c3)
Like I said, I have tried downloading it again, even creating a whole new notebook and installing everything anew (But it seems like the files got passed onto the new one as well, since they didn't need to download when launching), but to no avail.
**Full Console Log**

*Input:*

!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus

!wget -c https://civitai.com/api/download/models/293413 -O ./models/checkpoints/timeless.safetensors

!python entry_with_update.py --share

*Output:*

Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
--2024-01-25 13:34:23--  https://civitai.com/api/download/models/293413
Resolving civitai.com (civitai.com)... 104.18.22.206, 104.18.23.206, 2606:4700::6812:16ce, ...
Connecting to civitai.com (civitai.com)|104.18.22.206|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: /login?returnUrl=%2Fmodel-versions%2F293413&reason=download-auth [following]
--2024-01-25 13:34:23--  https://civitai.com/login?returnUrl=%2Fmodel-versions%2F293413&reason=download-auth
Reusing existing connection to civitai.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./models/checkpoints/timeless.safetensors’

./models/checkpoint     [ <=>                ] 114.83K  --.-KB/s    in 0.04s   

2024-01-25 13:34:24 (2.57 MB/s) - ‘./models/checkpoints/timeless.safetensors’ saved [117583]

Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865/
Total VRAM 15102 MB, total RAM 52218 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention
Running on public URL: https://01df501263681a5fc4.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
2024-01-25 13:34:30.629305: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-25 13:34:30.629358: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-25 13:34:30.630753: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-25 13:34:31.711098: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: /content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.60 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or https://01df501263681a5fc4.gradio.live/
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 8638922772201521132
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Traceback (most recent call last):
  File "/content/Fooocus/modules/patch.py", line 459, in loader
    result = original_loader(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Fooocus/modules/async_worker.py", line 823, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 373, in handler
    pipeline.refresh_everything(refiner_model_name=refiner_model_name, base_model_name=base_model_name,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/default_pipeline.py", line 233, in refresh_everything
    refresh_base_model(base_model_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/default_pipeline.py", line 69, in refresh_base_model
    model_base = core.load_model(filename)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/core.py", line 151, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings)
  File "/content/Fooocus/ldm_patched/modules/sd.py", line 427, in load_checkpoint_guess_config
    sd = ldm_patched.modules.utils.load_torch_file(ckpt_path)
  File "/content/Fooocus/ldm_patched/modules/utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/content/Fooocus/modules/patch.py", line 475, in loader
    raise ValueError(exp)
ValueError: Error while deserializing header: HeaderTooLarge
File corrupted: /content/Fooocus/models/checkpoints/timeless.safetensors 
Fooocus has tried to move the corrupted file to /content/Fooocus/models/checkpoints/timeless.safetensors.corrupted 
You may try again now and Fooocus will download models again. 

Total time: 0.06 seconds
--------------------------------------------------------------------------
Thanks in advance

**Comment by eddyizm** [comment] 2024-01-25 14:35
This is an issue with https://civitai.com. I was having that issue yesterday myself. I usually try to download the files I like locally. Then I will upload it directly from my desktop.

**Comment by Fahadxx** [comment] 2024-01-25 15:24
Same issue, suddenly happened less than 24 hours ago like suddenly, here is what I understand so far:

- models do "download" yet when using verbos it shows that its weirdly EXTREMELY faster than usual suggesting that it didn't
- they all are downloaded as login.72 (iterative)
- they are then listed under Hypernetworks instead of Models, loras, etc..
- Loras made by me and stored in google Drive work perfectly fine still unlike civitai links

I assume the issue is login related from civitai's side like a new requirement or something but if anyone got a solution it'll be highly appreciated

**Comment by eddyizm** [comment] 2024-01-25 15:43
Also the url format I use is a little different 
`https://civitai.com/api/download/models/138296?type=Model&format=SafeTensor`

**Comment by MasterRed0** [comment] 2024-01-25 17:52
Quick question,
How can I move the files I upload from my PC to the correct folder? When I upload them they're just stuck in the bottom of the column with files. 
![Zrzut ekranu 2024-01-25 185114](https://github.com/lllyasviel/Fooocus/assets/155583984/bedac8e5-6cf4-4e23-b94e-35a55165d593)
Thanks

**Comment by mashb1t** [comment] 2024-01-25 17:56
This could have many reasons. The output shows that either one of the following points were the case:
- the model author or civitai have set the model to "protected with auth"
- Civitai model was down/inaccessible and fallback is login URL
- Civitai has globally enabled a login mask, maybe due to high traffic/hacks/privacy(?!)

Just tested Colab again and it's working flawlessly with all the base models (from HuggingFace).

The issue persists though, i assume civitai has made login auth mandatory for everyone (tested with Juggernaut and a few different models). This is why the core models of Fooocus are hosted on HF as they did never have restrictions unless explicitly set per repository (i remember Llama2 being behind auth).

A workaround is to download from a mirror / different source (e.g. HF or private mirror), download after logging in (local solution) or manually upload to Google Drive and link the storage then.

As there is nothing we can do on Fooocus side i'd propose to close this issue, but waiting for your feedback.

**Comment by Fahadxx** [comment] 2024-01-25 17:59
"How can I move the files I upload from my PC to the correct folder?"

best practice is to upload it to your google drive and put the link of it in the lora/model links input before running the model, either this or just hold it with your mouse and drop it in the right directory (models/checkpoints)

**Comment by eddyizm** [comment] 2024-01-25 18:18
> Quick question,
> How can I move the files I upload from my PC to the correct folder? When I upload them they're just stuck in the bottom of the column with files. 
> ![Zrzut ekranu 2024-01-25 185114](https://github.com/lllyasviel/Fooocus/assets/155583984/bedac8e5-6cf4-4e23-b94e-35a55165d593)
> Thanks

You want to click on the checkpoint  folder so it uploads to that directory.  As far as I can tell you can't move the file using the ui. You can move it using a command in the notebook.

**Comment by thekingbalXD** [comment] 2024-01-25 18:20
Use !curl command:
!curl -Lo /content/Fooocus/models/checkpoints/*Model's name*.safetensors *Civitai url*

For example: 
!curl -Lo /content/Fooocus/models/checkpoints/nightvision.safetensors https://civitai.com/api/download/models/247444?type=Model&format=SafeTensor&size=pruned&fp=fp16

**Comment by MasterRed0** [comment] 2024-01-25 18:23
I got it... I attached my Drive and dragged the files from the Drive folder.
Everything seems to be working correctly now,
Thanks everyone

**Closed** 2024-01-25 18:41 UTC
Labels: wontfix

**Comment by kelseyaubrecht** [comment] 2024-01-26 02:40
In case anyone else runs into issues downloading, you can still use wget if you include your Civit API token.
```
def downloadModel(model_id, model_name):
  !curl -L -H 'Authorization: Bearer <YOUR_TOKEN__HERE>' -o ./models/checkpoints/{model_name}.safetensors https://civitai.com/api/download/models/{model_id}
```

**Comment by Fahadxx** [comment] 2024-01-27 02:37
for people using web ui in colab, I made this fix and it works :)



look for the code snippet:


1- get an api key from Civitai
----------------
2- add this code under it: 


def add_token_to_civitai_url(urls, token):
    # Split the input string into individual URLs
    url_list = urls.split(',')

    # Process each URL
    processed_urls = []
    for url in url_list:
        # Check if the URL is from civitai.com
        if "civitai.com" in url:
            # Check if URL already has a query parameter
            if '?' in url:
                # Append the token with an ampersand
                url += "&token=" + token
            else:
                # Append the token with a question mark
                url += "?token=" + token
        
        processed_urls.append(url)

    # Recombine the processed URLs into a single string
    return ','.join(processed_urls)

# Token to be added
token = ""  #@param {type:"string"}

# Process the URLs and get the updated string
updated_urls = add_token_to_civitai_url(custom_urls, token)




-----------
3- then edit this:
model_url+=custom_urls +", " if custom_urls else ""

to this:
model_url+=updated_urls+", " if updated_urls else ""
