### ISSUE TITLE
Error Expecting value: line 1 column 1 (char 0

### ISSUE THREAD

**Issue by xiaoyao-dev** [lllyasviel/Fooocus#1889] opened 2024-01-12 01:05 UTC
Error
Expecting value: line 1 column 1 (char 0)

**Comment by mashb1t** [comment] 2024-01-12 07:03
Please provide more context, e.g. your full terminal output, the type of device you're using, cloud/native and describe your actions leading to this behavior.
Keep in mind that the Websocket connection may suddenly stop when you're on a mobile device.

**Comment by mashb1t** [comment] 2024-01-13 10:56
Duplicate of https://github.com/lllyasviel/Fooocus/issues/92 and [a few more](https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+line+1+column+1+is%3Aclosed). Please check https://github.com/lllyasviel/Fooocus/issues/92#issuecomment-1706827413 and make sure your Websocket connection doesn't break while generating.

**Closed** 2024-01-13 11:01 UTC
Labels: duplicate
