### ISSUE TITLE
Generate image page not displaying

### ISSUE THREAD

**Issue by outsami-9527** [lllyasviel/Fooocus#1396] opened 2023-12-14 11:25 UTC
![jietu](https://github.com/lllyasviel/Fooocus/assets/147789176/f794a995-f4e0-409d-9595-0000cff18e2a)
![qq2](https://github.com/lllyasviel/Fooocus/assets/147789176/fe104834-70b6-4795-958e-0d1ec372745e)

Actually, the image has already been generated. In the early days, this phenomenon also occurred in Focus, but it was not frequent, but in recent versions, it has appeared a lot.

**Comment by mashb1t** [comment] 2023-12-29 01:03
Duplicate of https://github.com/lllyasviel/Fooocus/issues/948, implemented in https://github.com/lllyasviel/Fooocus/pull/1013

**Closed by mashb1t** 2023-12-29 01:03 UTC
Labels: duplicate
