### ISSUE TITLE
Don't use built-in VAE

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [lllyasviel/Fooocus#4] opened 2023-08-12 05:42 UTC
The built in VAE is watermarked and degrades image quality, leading to noticeable aliasing and chromatic aberration like effects, as seen in this example https://i.imgur.com/SCY5P5z.png .

**Comment by AshtakaOOf** [comment] 2023-08-12 07:58
Changing VAEs will not change the watermark on SDXL.

**Comment by lllyasviel** [comment] 2023-08-12 14:47
Hello @IdiotSandwichTheThird  and @AshtakaOOf , we are aware of the opinions of XL’s VAE is watermarked by some methods.

Nevertheless, we do not have enough evidences to support this. We do not know any existing research or methods that can watermark a latent diffusion’s first stage model.

The artifacts in your images are probably caused by the distribution of training data of XL’s vae. The XL’s vae is (likely to be) trained with many images with crisp and sharp texts in it so that its performance can be better for encoding/decoding texts, and the downside is probably some of your mentioned “chromatic aberration” because those training images have many “subpixels” for crisp and sharp texts.

Feel free to take a look at “subpixels” https://en.wikipedia.org/wiki/Subpixel_rendering to understand the “chromatic aberration” and text rendering, and this probably explains XL’s vae behaviors.

Finally, if anyone has stronger evidences to support the claim of “vae watermark”, please let us know.

**Comment by VolaNova** [comment] 2023-08-12 15:03
The VAE issue with "watermarking" was an error that was fixed 2 days after the SDXL 1.0 release, if you download the model or VAE from their repository after that time then there will be no "watermarking" effect as the model's baked VAE has been reverted to the .9 version and re-uploaded.

**Comment by MoonRide303** [comment] 2023-08-12 17:45
@lllyasviel Stability AI released official SDXL 1.0 with VAE from 0.9 to solve artifacts problems in their original repo ([sd_xl_base_1.0_0.9vae.safetensors](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors) and [sd_xl_refiner_1.0_0.9vae.safetensors](https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0_0.9vae.safetensors)) - you can check out discussion in [diffusers issue #4310](https://github.com/huggingface/diffusers/issues/4310), or just compare some images from original, and fixed release by yourself. By default I'd suggest to go with updated versions (those with VAE from 0.9).

**Comment by lllyasviel** [comment] 2023-08-12 18:39
This looks more convincing. We will have some actions on this.

**Comment by lllyasviel** [comment] 2023-08-12 18:47
fixed in 1.0.17

https://github.com/lllyasviel/Fooocus/blob/main/update_log.md

**Closed** 2023-08-13 22:47 UTC
