### ISSUE TITLE
I puted the pth upscaler but nothing change i dont see it 

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1697] opened 2024-01-01 12:24 UTC
![image](https://github.com/lllyasviel/Fooocus/assets/42430868/72cfd6dd-ffe6-423b-8094-f871a2032440)

**Comment by mashb1t** [comment] 2024-01-01 14:41
The upscaler model is hardcoded. If you want to change this you'll have to also change the model name in the code.
See 2 occurrences here: https://github.com/search?q=repo%3Alllyasviel%2FFooocus%20fooocus_upscale&type=code

Enhancement: make upscaler model configurable / selectable in Developer Debug Mode

**Comment by Amit30swgoh** [comment] 2024-01-01 18:45
> The upscaler model is hardcoded. If you want to change this you'll have to also change the model name in the code or name your upscaler like the existing one, creating a backup of the existing one before. See 2 occurrences here: https://github.com/search?q=repo%3Alllyasviel%2FFooocus%20fooocus_upscale&type=code
> 
> Enhancement: make upscaler model configurable / selectable in Developer Debug Mode

Thanks very much

**Comment by mashb1t** [comment] 2024-01-04 23:49
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1510

**Closed by mashb1t** 2024-01-04 23:49 UTC
Labels: enhancement
