### ISSUE TITLE
Use the same name for release zip files?

### ISSUE THREAD

**Issue by SoftologyPro** [lllyasviel/Fooocus#308] opened 2023-08-30 21:35 UTC
Reason being is that the install can be easily scripted.
With the zip name and path changed every release it breaks the ability to automate the download/unzip/install process.

**Comment by mashb1t** [comment] 2024-01-01 16:34
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/507

**Closed by mashb1t** 2024-01-01 16:34 UTC
