### ISSUE TITLE
[Feature Request]: can the fooocus log add "Inpaint Denoising Strength" and "Inpaint Respective Field"

### ISSUE THREAD

**Issue by BNP1111** [lllyasviel/Fooocus#2550] opened 2024-03-17 11:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

can the fooocus log add "Inpaint Denoising Strength" and "Inpaint Respective Field", sometimes really important

### Proposed workflow

add "Inpaint Denoising Strength" and "Inpaint Respective Field"

**Comment by mashb1t** [comment] 2024-03-17 13:12
more or less duplicate of https://github.com/lllyasviel/Fooocus/issues/1725. Image Prompt parameters aren't currently added to history log or metadata due to lack of reproducibility with the click of one button. Users will nevertheless not be able to reproduce the results ithout separate image input or mask upload, which is why this is not implemented.
This might be considered in the future when demand is high enough.

**Closed by mashb1t** 2024-03-17 13:12 UTC
Labels: enhancement, triage
