### ISSUE TITLE
What time can we achieve video generation from text?

### ISSUE THREAD

**Issue by andywang2014** [lllyasviel/Fooocus#2206] opened 2024-02-08 14:00 UTC
What time can we achieve video generation from text?

**Comment by eddyizm** [comment] 2024-02-08 16:14
I believe there are other tools specialized for that. Not sure if the dev team has it on the roadmap.

**Comment by mashb1t** [comment] 2024-02-08 22:46
closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1031

**Closed by mashb1t** 2024-02-08 22:46 UTC
