### ISSUE TITLE
Error installing foocus

### ISSUE THREAD

**Issue by gauravandkarthikdevelopers** [lllyasviel/Fooocus#2583] opened 2024-03-20 14:18 UTC
### Checklist

- [x] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [x] The issue has not been reported before recently
- [x] The issue has been reported before but has not been fixed yet

### What happened?

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      + meson setup C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da
      Build dir: C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      Activating VS 17.9.3
      C compiler for the host machine: cl (msvc 19.39.33522 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x64")
      C linker for the host machine: link link 14.39.33522.0
      C++ compiler for the host machine: cl (msvc 19.39.33522 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x64")
      C++ linker for the host machine: link link 14.39.33522.0
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
      Library m found: NO

      ..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(fooocus_env) PS C:\Users\gaura\OneDrive\Desktop\project-nidha\Fooocus>

### Steps to reproduce the problem

try to install

### What should have happened?

it should have installed pip requirements

### Where are you running Fooocus?

None

### Console logs

```Shell
× Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      + meson setup C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj\meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da
      Build dir: C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      Activating VS 17.9.3
      C compiler for the host machine: cl (msvc 19.39.33522 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x64")
      C linker for the host machine: link link 14.39.33522.0
      C++ compiler for the host machine: cl (msvc 19.39.33522 "Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33522 for x64")
      C++ linker for the host machine: link link 14.39.33522.0
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO (cached)
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
      Library m found: NO

      ..\meson.build:57:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\gaura\AppData\Local\Temp\pip-install-vyte2srh\scipy_3bb1ec3647bd46f8a1f0bec4fd0ad0da\.mesonpy-7u9havvj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(fooocus_env) PS C:\Users\gaura\OneDrive\Desktop\project-nidha\Fooocus>
```

**Comment by mashb1t** [comment] 2024-03-20 20:20
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1930, see comment https://github.com/lllyasviel/Fooocus/issues/1930#issuecomment-1891108667.

**Closed by mashb1t** 2024-03-20 20:20 UTC
Labels: bug, triage
