### ISSUE TITLE
Is it possible to make in the future that the style's prompt is included in the HTML log history?

### ISSUE THREAD

**Issue by nyukers** [lllyasviel/Fooocus#2233] opened 2024-02-11 08:07 UTC
Hi author,

is it possible to make in the future that the **style's prompt** is included in the HTML log history?
This would help users understand how styles affect each other.

Thank you.

**Comment by mashb1t** [comment] 2024-02-11 08:34
Yes. Duplicate of https://github.com/lllyasviel/Fooocus/issues/1995, implementation in https://github.com/lllyasviel/Fooocus/pull/1920.

**Closed by mashb1t** 2024-02-11 08:34 UTC
