### ISSUE TITLE
Please add the ability to inpaint faces like reactor

### ISSUE THREAD

**Issue by zono50** [lllyasviel/Fooocus#1935] opened 2024-01-15 03:09 UTC
There are many times when I have a perfect image, and want to inpaint someones face on it, but i can't. Using faceswap and ip adapter are close, but can't really seem to get the results I want. If we could add another drop down to the metho drop down for inpainting that uses something like reactor or faceswap, that would be amazing.

**Comment by bhuisman1992** [comment] 2024-01-15 07:59
Did you try this?
Use input image --> use a base image for reference and put it on faceswap (default settings)
After you've done this go to input image --> inpaint/outpaint --> set the method to improve detail
In the extra input box type things about the face like: girl with freckles for example
Go to advanced --> advanced --> developer debug mode --> control --> check the "Mixing Image Prompt and Inpaint" checkbox.

By doing this (with the right styles selected) i get pretty much the same face each time!

**Comment by ItsCrea** [comment] 2024-01-15 08:37
Fooocus faceswap even with high values of weight and control step does not give full recognition of the face. However, it recognizes the general features of the face, the shape of the head, etc. very well. A very good result is given by the Fooocus faceswap + FaceFusion combination. It would be cool if FaceFusion (or similar) was built right into Fooocus.

**Comment by zono50** [comment] 2024-01-15 12:17
@bhuisman1992 Thanks for the great tip. Going to try this today

**Comment by mashb1t** [comment] 2024-01-15 12:44
Closing as potential duplicate of https://github.com/lllyasviel/Fooocus/issues/1522 and already integrated.
Anyways: @zono50 please let us know the results of your testing! :)

**Closed by mashb1t** 2024-01-15 12:44 UTC

**Comment by mashb1t** [comment] 2024-01-15 13:17
1. this depends on the inpaint method and your use case. "Improve Detail (face, hand, eyes, etc.)" will only modify up to a specific degree, while "Modify Content (add objects, change background, etc.)" will straight up add completely new content.
2. Fooocus can't handle inpainting of multiple faces at once. The currentl workflow is to modify the image individually face by face and use the generated result as input for the next inpainting cycle by drag&dropping it down again.
