### ISSUE TITLE
Obtain PNGs with transparent background

### ISSUE THREAD

**Issue by lilo-san** [lllyasviel/Fooocus#2728] opened 2024-04-07 16:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

The goal is to obtain the PNGs with transparent background instead of white.

This is to help when requesting to the AI objects or characters to integrate in other backgrounds, etc...

Thanks for taking the time to check if this is doable.

### Proposed workflow

1. Select PNG with transparency as an output format

**Comment by mashb1t** [comment] 2024-04-07 17:49
Duplicate of https://github.com/lllyasviel/Fooocus/issues/2403, please have a look there.

**Closed by mashb1t** 2024-04-07 17:49 UTC
Labels: enhancement, triage
