### ISSUE TITLE
Add concurrency support

### ISSUE THREAD

**Issue by canytam-krystal** [lllyasviel/Fooocus#1894] opened 2024-01-12 08:47 UTC
**Is your feature request related to a problem? Please describe.**
In order to support more client connection, I want to add the concurrency support to Fooocus. I had tried to add parameter "concurrency_count=N" to the queue() function but the gradio still queue the request.

**Describe the idea you'd like**
Add a parameter to control the number of concurrency request so the client do not need to wait too long to start.

**Comment by mashb1t** [comment] 2024-01-12 17:50
Thank you for providing your ideas, much appreciated.
This is already on the list of potential future enhancements (more or less, concurrency_count might or might not be used and made configurable, as Fooocus currently only supports one GPU + one worker at a time).
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/292.

**Closed by mashb1t** 2024-01-12 17:50 UTC
