### ISSUE TITLE
[Bug]: Kaggle Installation error

### ISSUE THREAD

**Issue by ATJ79** [lllyasviel/Fooocus#3064] opened 2024-05-31 16:53 UTC
### Checklist

- [x] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hey! During installation of Fooocus on Kaggle using this [notebook](https://www.kaggle.com/code/pogscafe/fooocus) I faced some errors. After verifying and activating GPU in Kaggle, I tried to install but first of all it showed "Couldn't open requirement files" error. Then it shows warnings and after showing a lot of codes, it finally gives "Download error (28) Timeout was reached
Could not resolve host: conda.anaconda.org"
I attach error images
![Screenshot 2024-05-30 230939](https://github.com/lllyasviel/Fooocus/assets/123479832/4b32d7db-7f29-4be3-b324-9c6b891f4c13)
![Screenshot 2024-05-31 190431](https://github.com/lllyasviel/Fooocus/assets/123479832/df22c55a-3f94-4972-ab51-1feb1f0b478d)

### Steps to reproduce the problem

1. Create Kaggle account
2. Find Fooocus for Kaggle notebook and choose edit and copy
3. Run the first code and the errors will pop up

### What should have happened?

It should finish the installation successfully

### What browsers do you use to access Fooocus?

Brave

### Where are you running Fooocus?

Cloud (Kaggle)

### What operating system are you using?

Windows 11

### Console logs

```Shell
/kaggle/working
Cloning into 'Fooocus'...
fatal: unable to access 'https://github.com/lllyasviel/Fooocus.git/': Could not resolve host: github.com
[Errno 2] No such file or directory: 'Fooocus'
/kaggle/working
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_versions.txt'
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x780677f288e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x780677f28be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x780677f28e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x780677f29030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x780677f291e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /whl/cu117/torch/
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x78986bcc0610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x78986bcc07c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x78986bcc0d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x78986bcc0f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x78986bcc10c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pyyaml/
ERROR: Could not find a version that satisfies the requirement pyyaml (from versions: none)
ERROR: No matching distribution found for pyyaml

Looking for: ['openssh']

warning  libmamba Cache file "/opt/conda/pkgs/cache/c6f2354e.json" was modified by another program

Download error (28) Timeout was reached [https://conda.anaconda.org/rapidsai/noarch/repodata.json]
Could not resolve host: conda.anaconda.org

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 884, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 756, in do_call
        exit_code = install(args, parser, "install")
      File "/opt/conda/lib/python3.10/site-packages/mamba/mamba.py", line 468, in install
        index = load_channels(pool, channels, repos)
      File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
        index = get_index(
      File "/opt/conda/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/rapidsai/noarch/repodata.json]
    Could not resolve host: conda.anaconda.org

`$ /opt/conda/bin/mamba install openssh -y`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-
                          gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/li
                          b:/usr/local/nvidia/lib64:/opt/conda/lib
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs:/opt/conda/lib
                     PATH=/opt/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr
                          /local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
               PYTHONPATH=/kaggle/lib/kagglegym:/kaggle/lib
           PYTHONUSERBASE=/root/.local
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
           TESSERACT_PATH=/usr/bin/tesseract

     active environment : None
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
                          /root/.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=skylake_avx512
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=5.15.133=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/rapidsai/linux-64
                          https://conda.anaconda.org/rapidsai/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.10.12 Linux/5.15.133+ ubuntu/22.04.3 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

**Comment by mashb1t** [comment] 2024-05-31 18:38
There is no official Fooocus for Kaggle notebook and it seems like the one you use or in general Kaggle has issues connecting to the internet (github/conda resolution issues).
Closing this one as not a bug of Fooocus, but the infrastructure. Please ensure to either first download everything or enable internet / DNS access.

**Closed by mashb1t** 2024-05-31 18:38 UTC
Labels: bug, triage

**Comment by xawwnee** [comment] 2024-10-27 08:40
is it fixed now?
