### ISSUE TITLE
[Bug]: Unable to generate Gradio public url

### ISSUE THREAD

**Issue by raahulgupta07** [lllyasviel/Fooocus#2817] opened 2024-04-27 07:00 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 
<img width="1180" alt="Screenshot 2024-04-27 at 1 26 50 PM" src="https://github.com/lllyasviel/Fooocus/assets/8269398/453cce9f-d741-4517-b80b-13b242570bd0">
<img width="1180" alt="Screenshot 2024-04-27 at 1 26 50 PM" src="https://github.com/lllyasviel/Fooocus/assets/8269398/453cce9f-d741-4517-b80b-13b242570bd0">

### Steps to reproduce the problem

when i in run the below command i am getting the attached error in google colab till yesterday everything was working fine i am facing this issue since today 

!python entry_with_update.py --share --always-high-vram

### What should have happened?

--

### Where are you running Fooocus?

None

### Console logs

```Shell
--
```

### Additional information

--

**Comment by DeepakNIEMysuru** [comment] 2024-04-27 07:55
After adding the downloaded file to the location mentioned below 

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio
Running on [https://localhost:7865/](https://4ila2bzoklp-496ff2e9c6d22116-7865-colab.googleusercontent.com/)

Due to antivirus the system won't download the file. When I downloaded the file in other system, It got downloaded and after adding it to path, Still the error persists..

**Comment by poor7** [comment] 2024-04-27 08:22
Today the Gradio Share API crashes periodically. Because of this, an error is displayed and the link is not created.
https://status.gradio.app/793595965

**Comment by DeepakNIEMysuru** [comment] 2024-04-27 09:06
Hi Lllyasviel/Fooocus,

Thanks for the update & Gradio spelling is wrong in the bug name, modify it.



Thanks & Regards,
Deepak P,
Assistant Professor,
Department of Computer Science and Engineering
The National Institute of Engineering, Mysuru
Mobile No. : +91 7353641871

**Comment by dmitryalexander** [comment] 2024-04-27 11:39
i'm wondering, how difficult would it be to rewrite the fooocus code so that it works with cloudflare or localtunnel?

**Comment by KirtiKousik** [comment] 2024-04-27 13:08
It's working now. There was a problem with gradio share api.

**Comment by mashb1t** [comment] 2024-04-27 13:43
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2815

**Closed by mashb1t** 2024-04-27 13:43 UTC
Labels: bug, triage

**Comment by jwfool** [comment] 2024-04-27 17:33
This is still broken as of right now, same error

**Comment by killergod143** [comment] 2024-04-28 07:43
@dmitryalexander Perfect working solution , nicely explained

**Comment by adumont** [comment] 2024-04-28 16:22
Still happening to me .... Will try the cloudflared alternative for now...

**Comment by Al-Rien** [comment] 2024-04-28 19:04
Where do these silly mistakes come from? There's simply nothing to break there.

**Comment by ishandhanani** [comment] 2024-04-29 22:30
Hitting this at the moment
