### ISSUE TITLE
multi gpu support or gpu selection / increase maximum image generation number

### ISSUE THREAD

**Issue by sfingali** [lllyasviel/Fooocus#191] opened 2023-08-18 11:19 UTC
I have 2 x 3090s - what would be great is to be able to use both the gpus in image generation at the same time. I can do this manually if you could select the GPU and launch two sessions, one on each GPU. By internally would be great as well.

Additionally, the maximum image generation is 32. For running multiple images overnight, much higher numbers would be useful.

Fantastic program.

**Comment by barepixels** [comment] 2023-08-18 16:27
If you want a quick hack, you can edit line 61 of webui.py

image_number = gr.Slider(label='Image Number', minimum=1, maximum=32, step=1, value=2)

**Comment by mzawdx2022** [comment] 2023-08-19 01:17
hack it easy

**Comment by mashb1t** [comment] 2024-01-01 19:40
Duplicate of https://github.com/lllyasviel/Fooocus/issues/292, parallel support has not yet been implemented.
The maximum image amount can now be set using the config.txt.

**Closed by mashb1t** 2024-01-01 19:40 UTC
