### ISSUE TITLE
[Feature Request]: Support for Flux1-Dev-bnb-nf4 in Foocus

### ISSUE THREAD

**Issue by magekinnarus** [lllyasviel/Fooocus#3496] opened 2024-08-11 13:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

with the drop of Flux1 nf4 optimization, I think it is time to add support for it in Fooocus as well.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by mashb1t** [comment] 2024-08-11 13:35
Duplicate of https://github.com/lllyasviel/Fooocus/issues/3424, but thanks for your interest!

**Closed by mashb1t** 2024-08-11 13:35 UTC
Labels: enhancement, triage
