### ISSUE TITLE
[Bug]: No longer getting a Public URL

### ISSUE THREAD

**Issue by Sxbelec** [lllyasviel/Fooocus#2825] opened 2024-04-27 16:05 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

upon running this code we are no longer getting the gradio.live Public URL.
earlier both Local and Public URL were present but now only Local URL

### Steps to reproduce the problem

1. Start Script
2. Observe there is No Public URL with gradio.live instead a 'none' placeholder

### What should have happened?

Public URL should have been present along with Local Url

### What browsers do you use to access Fooocus?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

Windows 11

### Console logs

```Shell
Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.22)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 15102 MB, total RAM 12979 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention
2024-04-27 15:29:50.455385: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-27 15:29:50.455444: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-27 15:29:50.461535: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-27 15:29:52.611072: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.66 seconds
Started worker with PID 2113
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or None
```

**Comment by GabrScar** [comment] 2024-04-27 16:30
Same issue, is this a problem with Gradio or Foocus?

**Comment by dmitryalexander** [comment] 2024-04-27 16:32
> Same issue, is this a problem with Gradio or Foocus?

it's a problem with gradio, but, you can use cloud flare instead, but it's slower

**Comment by GabrScar** [comment] 2024-04-27 16:56
Does this type of problem usually get resolved quickly?

**Comment by dmitryalexander** [comment] 2024-04-27 16:59
> Does this type of problem usually get resolved quickly?

gradio has never went down as far as i can remember. so, at least for 90 days prior to 12 am yesterday, this hasn't happened.

**Comment by dmitryalexander** [comment] 2024-04-27 17:00
> Does this type of problem usually get resolved quickly?

you can try to do a work around by modifying some files and launching into CloudFlare instead of Gradio

> same issue..

Here's how you solve the problem.

Go to the google colab..

add these two lines at the top.

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

comment out the launch.py line
![Screenshot 2024-04-27 080319](https://github.com/lllyasviel/Fooocus/assets/75273036/00eb701d-5231-40e1-a7ea-2b193fd28868)

like this...


then it will clone the repo... Next, find the file in your google colab called webui.py
![Screenshot 2024-04-27 080547](https://github.com/lllyasviel/Fooocus/assets/75273036/32b44fab-6734-4047-84d2-d530c296233e)

at the very bottom of the webui.py file.... find the line that says: shared.gradio_root.launch(

and paste this code right BEFORE it.

import subprocess
import threading
import time
import socket

def iframe_thread(port):
    while True:
        time.sleep(0.5)
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex(('127.0.0.1', port))
        if result == 0:
            break
        sock.close()
    print("\nFooocus finished loading, trying to launch cloudflared (if it gets stuck here cloudflared is having issues)\n")
    p = subprocess.Popen(["cloudflared", "tunnel", "--url", "http://127.0.0.1:{}".format(port)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    for line in p.stderr:
        l = line.decode()
        if "trycloudflare.com" in l:
            print("This is the URL to access Fooocus:", l[l.find("https"):], end='')

port = 7865  # Replace with the port number used by Fooocus
threading.Thread(target=iframe_thread, daemon=True, args=(port,)).start()


also change the code inside of shared.gradio_root.launch( 
TO
shared.gradio_root.launch(
    inbrowser=args_manager.args.in_browser,
    server_name=args_manager.args.listen,
    server_port=args_manager.args.port,
    allowed_paths=[modules.config.path_outputs],
    blocked_paths=[constants.AUTH_FILENAME]
)

original webui.py file
![Screenshot 2024-04-27 080723](https://github.com/lllyasviel/Fooocus/assets/75273036/c8014c2e-d91d-40c3-93e5-ee7592f79a54)

modified webui.py file
![Screenshot 2024-04-27 080825](https://github.com/lllyasviel/Fooocus/assets/75273036/2a4341f8-ea63-4291-ba7e-ce7e768104df)

uncomment the entry.py line in google Collab
![Screenshot 2024-04-27 080838](https://github.com/lllyasviel/Fooocus/assets/75273036/95d91912-dac2-4655-b6b5-bc8857e453dc)

Hit PLAY.

**Comment by petyaaa6** [comment] 2024-04-27 18:50
still not working...

**Comment by petyaaa6** [comment] 2024-04-27 18:52
and the changing the webui.py also doesn't solve the issue...

**Comment by igninjaz** [comment] 2024-04-27 19:23
still not working. @lllyasviel help.

**Comment by GabrScar** [comment] 2024-04-27 19:55
@lllyasviel

**Comment by mashb1t** [comment] 2024-04-28 05:15
It's working again,  the Gradio Sharing API was down.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2815

**Closed by mashb1t** 2024-04-28 05:15 UTC
Labels: bug, triage
