### ISSUE TITLE
Black Image After some steps on Mac

### ISSUE THREAD

**Issue by rutsguifd** [lllyasviel/Fooocus#1971] opened 2024-01-18 13:52 UTC
**At some point when generating image turns black**

**Problem**
At some point when generating image turns black

first steps are going okay:
[Image Before](https://prnt.sc/hwN57hzfOZ3T)

but on 10-20 step it just turns black. tried some settings and commands while running but no help:
[Image After](https://prnt.sc/tKMVXFoM7xAx)

**Specs**
MacBook Pro on M1 Max (max cpu/gpu spec) with 32gb ram. Mac OS 12

ps: checked briefly issues but couldnt find help there. where some similar issues but it didnt help

**Comment by mashb1t** [comment] 2024-01-18 22:47
This is a duplicate of https://github.com/lllyasviel/Fooocus/issues/1184, where there currently is no official solution but potential workarounds. Feel free to check out https://github.com/lllyasviel/Fooocus/issues/1184#issuecomment-1885579002 and linked PRs / Issues.

**Closed** 2024-01-18 22:49 UTC
Labels: duplicate
