### ISSUE TITLE
What should  I do?

### ISSUE THREAD

**Issue by choudhary3301** [lllyasviel/Fooocus#1902] opened 2024-01-12 15:51 UTC
CUDA out of memory. Tried to allocate 10.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 1.57 GiB is free. Of the allocated memory 3.24 GiB is allocated by PyTorch, and 154.45 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by mashb1t** [comment] 2024-01-12 17:14
> **Read Troubleshoot**
> 
> [x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

You've deleted this paragraph when creating the issue.
Please make sure to read it and you will find the solution there.
Closing as duplicate of [this list of issues](https://github.com/lllyasviel/Fooocus/issues?q=is%3Aissue+%22CUDA+out+of+memory%22+is%3Aclosed+)

**Closed by mashb1t** 2024-01-12 17:14 UTC
