### ISSUE TITLE
Video, Animations

### ISSUE THREAD

**Issue by Fedebat99** [lllyasviel/Fooocus#1711] opened 2024-01-02 08:39 UTC
It would be nice to be able to create mini animations or videos, facial expressions, additional effects etc...

**Comment by Krupakar-Reddy-S** [comment] 2024-01-02 09:45
I am pretty sure the current setup of the code supports image only but there are [video generating models](https://stability.ai/stable-video) and they can be added in the future, if you want to try vide generation you can try [ComfyUI](https://github.com/comfyanonymous/ComfyUI), a node based Stable Diffusion app.

Video generation is just getting started and future models will support more length and frame output options, But it is just not there yet.

**Comment by mashb1t** [comment] 2024-01-02 12:26
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1031, it (at least) is in the backlog :)

**Closed** 2024-01-02 12:27 UTC
Labels: duplicate
