### ISSUE TITLE
Updated juggernaught to v8 but app won't let me delete the v6

### ISSUE THREAD

**Issue by patientx** [lllyasviel/Fooocus#2006] opened 2024-01-21 11:11 UTC
**Read Troubleshoot**

[x] I admit that I have read the Troubleshoot,

**Describe the problem**

While trying other sdxl models I saw that juggernaught is on version 8 now. Downloaded and started using it, but fooocus won't let the old one stay deleted. It redownloads v6 if it can't find it checkpoints. For a workaround I created an empty file and named it as v6. Now the app starts but can we just change the default to v8 or any other model so we don't have to keep it in our models folder ?

**Comment by mashb1t** [comment] 2024-01-21 12:32
I've already created a PR, see https://github.com/lllyasviel/Fooocus/pull/1785, but changing the default model is based on intensive testing by the Fooocus core dev team to achieve best results. Please stay tuned.
JuggernautV6 is the default, please use a preset with JuggernautV8 and override the download models section.

**Comment by mashb1t** [comment] 2024-01-21 12:33
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1701

**Closed by mashb1t** 2024-01-21 12:33 UTC
