### ISSUE TITLE
Fooocus Extension Translate

### ISSUE THREAD

**Issue by AlekPet** [lllyasviel/Fooocus#2011] opened 2024-01-21 20:48 UTC
Hello. I created an extension for Fooocus that translates the entered prompt request from another language into English. I also had to write a patch so as not to rewrite the code in the webui.py file every time updates. Could you make it possible to add extensions or at least bring mine into focus. Because not everyone speaks English well. Thank you for your Fooocus.
[https://github.com/AlekPet/Fooocus_Extensions_AlekPet](https://github.com/AlekPet/Fooocus_Extensions_AlekPet)

**Comment by mashb1t** [comment] 2024-01-22 08:18
Thank you for your contribution. Prompt translation has already been requested a multitude of times and a PR is already open, see https://github.com/lllyasviel/Fooocus/pull/1039. Feel free to add your comments there!
Sonebody also has already implemented a local translate model as Google Translate is not available in Mainland China.

Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1024 and  https://github.com/lllyasviel/Fooocus/issues/983.

**Closed by mashb1t** 2024-01-22 08:18 UTC

**Comment by mashb1t** [comment] 2024-01-22 22:18
reference to discussion: https://github.com/lllyasviel/Fooocus/discussions/1660#discussioncomment-8194006
