### ISSUE TITLE
Add a "Mask Image Input" for inpainting feature.

### ISSUE THREAD

**Issue by YuWongXX** [lllyasviel/Fooocus#1438] opened 2023-12-16 05:23 UTC
Add a "Mask Image Input" for inpainting feature.

**Comment by kubilaykilinc** [comment] 2023-12-17 16:13
I wrote before this. I hope it can be

**Comment by mashb1t** [comment] 2023-12-29 00:02
Duplicate of https://github.com/lllyasviel/Fooocus/issues/879, implemented in PRs https://github.com/lllyasviel/Fooocus/pull/529 and https://github.com/lllyasviel/Fooocus/pull/1126

**Closed by mashb1t** 2023-12-29 00:02 UTC
