### ISSUE TITLE
[Bug]: Gradiolive link won't show anymore in Colab

### ISSUE THREAD

**Issue by adumont** [lllyasviel/Fooocus#2826] opened 2024-04-27 16:11 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When starting in Colab it won't give the gradiolive link any more.

Last line says:

`App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or None`

See full log below

### Steps to reproduce the problem

Open the Golab Notebook (https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb)
run and wait for the gradiolive link to appear

### What should have happened?

There should be a gradiolive link to connect to the Gradio interface.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
Collecting pygit2==1.12.2
  Downloading pygit2-1.12.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 13.7 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.22)
Installing collected packages: pygit2
Successfully installed pygit2-1.12.2
/content
Cloning into 'Fooocus'...
remote: Enumerating objects: 5855, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 5855 (delta 2), reused 12 (delta 1), pack-reused 5835
Receiving objects: 100% (5855/5855), 32.68 MiB | 26.25 MiB/s, done.
Resolving deltas: 100% (3373/3373), done.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.1
Error checking version for torchsde: No package metadata was found for torchsde
Installing requirements
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /content/Fooocus/models/vae_approx/xlvaeapp.pth

100% 209k/209k [00:00<00:00, 14.8MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt" to /content/Fooocus/models/vae_approx/vaeapp_sd15.pth

100% 209k/209k [00:00<00:00, 12.0MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xl-to-v1_interposer-v3.1.safetensors" to /content/Fooocus/models/vae_approx/xl-to-v1_interposer-v3.1.safetensors

100% 6.25M/6.25M [00:00<00:00, 114MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to /content/Fooocus/models/prompt_expansion/fooocus_expansion/pytorch_model.bin

100% 335M/335M [00:01<00:00, 262MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors

100% 6.62G/6.62G [00:37<00:00, 191MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors" to /content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors

100% 47.3M/47.3M [00:00<00:00, 244MB/s]
Total VRAM 15102 MB, total RAM 12979 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention
2024-04-27 16:09:01.533177: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-27 16:09:01.533237: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-27 16:09:01.655125: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-27 16:09:04.212024: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Base model loaded: /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.64 seconds
Started worker with PID 776
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or None
```

### Additional information

It worked fine at the beginning of today afternoon, I could create some images. Then I went back an hour later and it doesn't show the gradiolive URL anymore. Wondering if it's an issue on Gradio side?

**Comment by petyaaa6** [comment] 2024-04-27 18:50
still not working

**Comment by petyaaa6** [comment] 2024-04-27 18:52
and the changing the webui.py also doesn't solve the issue...

**Comment by animeshanand1** [comment] 2024-04-27 18:53
Still not working .

**Comment by claimcreative** [comment] 2024-04-27 19:48
at this time not working

**Comment by ballard11** [comment] 2024-04-27 20:00
Experiencing the same.

**Comment by GabrScar** [comment] 2024-04-27 20:13
"Gradio's latest update has a bug that  makes one of the needed filed seem like a potential threat so most sites wont run it or just abort when they reach to the file, there's nothing we can do about it but wait until it's fixe"

**Comment by KirtiKousik** [comment] 2024-04-28 03:51
Its working fine now. The problem was with the share API (https://status.gradio.app/793595965). You don't need to do anything or change any file names.

**Comment by mashb1t** [comment] 2024-04-28 05:16
It's working again, the Gradio Sharing API was down.
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2815

**Closed by mashb1t** 2024-04-28 05:16 UTC
Labels: bug, triage

**Comment by adumont** [comment] 2024-04-28 15:30
Still happening here, I've opened the Colab notebook https://colab.research.google.com/github/lllyasviel/Fooocus/blob/main/fooocus_colab.ipynb, and getting `App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or None`, still no gradiolive link

**Comment by adumont** [comment] 2024-04-28 15:32
> It's working again, the Gradio Sharing API was down. Closing as duplicate of #2815

at the time of me opening the issue yesterday, the Share API was not down annymore. I had been down earlier, but it was green at that time, when I check on Gradio Status (before opening the issue). And now it's also green but the problem is still there.
