### ISSUE TITLE
Fine tuning the Fooocus model

### ISSUE THREAD

**Issue by Anbu-Divum** [lllyasviel/Fooocus#2139] opened 2024-02-02 09:20 UTC
Hi @lllyasviel  and other, 

I'm so impressed with Fooocus model which is doing good work, but Although I want to custom training /fine tuning the model according to my dataset which I have stored locally. Can someone let me know how can I start fine tuning the model according to my requirement. I gone through many blogs and site where they used to discussed about fine tuning the model from huggingface pipeline.

Answers will be helpful for my education and research. Thanks & appreciate in advance

**Comment by eddyizm** [comment] 2024-02-02 19:27
As far as I know, you can't use fooocus to train a model, you may need a different tool to train a model or lora and then use it with fooocus.

**Comment by mashb1t** [comment] 2024-02-03 08:49
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1329 and https://github.com/lllyasviel/Fooocus/issues/2051, please check them out.

**Closed by mashb1t** 2024-02-03 08:49 UTC
