### ISSUE TITLE
[Feature Request]: update the image load panel to the latest gradio version

### ISSUE THREAD

**Issue by MokkaBoss1** [lllyasviel/Fooocus#2949] opened 2024-05-18 16:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

the latest gradio image load gives the ability to cut and paste from the clipboard more easily.

![image](https://github.com/lllyasviel/Fooocus/assets/136205220/17f16886-6b91-475a-8c2b-ed075f8b9ef9)

I know with the current version you can drag and drop an image into the corresponding widget but for example in affinity photo you can't drag across windows. But you can control shift C and then upload using the clipboard upload in this new widget.

### Proposed workflow

I know with the current version you can drag and drop an image into the corresponding widget but for example in affinity photo you can't drag across windows. But you can control shift C and then upload using the clipboard upload in this new widget.

### Additional information

nothing else

**Comment by mashb1t** [comment] 2024-05-18 16:42
duplicate of https://github.com/lllyasviel/Fooocus/issues/1012, see also https://github.com/lllyasviel/Fooocus/issues/2911 (https://github.com/lllyasviel/Fooocus/issues/2911#issuecomment-2108362279)

**Closed by mashb1t** 2024-05-18 16:42 UTC
Labels: enhancement, triage

**Comment by MokkaBoss1** [comment] 2024-05-18 17:52
many thanks for your consideration
