### ISSUE TITLE
[Bug]: Anime Preset is So Much Slower than Default Preset

### ISSUE THREAD

**Issue by codezeros** [lllyasviel/Fooocus#2490] opened 2024-03-09 15:50 UTC
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i have ran anime presets through a cmd argument when the fooocus ran it too much time before moving into gpu, as it if it's got stuck on waiting list also no problem with usage of GPU and CPU and RAM

![image](https://github.com/lllyasviel/Fooocus/assets/156826608/c60082da-ff2e-4ef2-8e80-4a97c1de011e)

### Steps to reproduce the problem

simply ran the anime preset with any multiple styles with a prompt describing more details for the image (not much problem with anime preset's default settings like "1girl" some times or default presets with any prompt does not have any problem)

### What should have happened?

it will ran just like the default model preset in performance

### Where are you running Fooocus?

Locally

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: D:\fooocus\models\checkpoints\animaPencilXL_v100.safetensors
Request to load LoRAs [['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\fooocus\models\checkpoints\animaPencilXL_v100.safetensors].
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.85 seconds
Started worker with PID 22232
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 7.0
[Parameters] Seed = 5766305042841033437
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a girl smiling in a park with her friends, bright, sunny, vibrant, intricate, highly detailed, light, dramatic, elegant, sharp focus, beautiful, clear, crisp, refined, artistic, innocent, inspired, pretty, charming, scientific, cute, adorable, magical, enchanted, enhanced, cool, joyful, background, illuminated, cinematic, complex, amazing, colorful
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] a girl smiling in a park with her friends, expressive, lively, new, exciting, unique, cute, confident, inspired, vibrant, color balanced, intricate, beautiful, strong, detailed, impressive, gorgeous, background light, dramatic, shiny, highly saturated, complex, lovely, colorful, attractive, pretty, illuminated, cinematic, epic, fine detail, rich colors
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.46 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 11.68 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 16.19 seconds
100%|██████████| 30/30 [00:15<00:00,  1.98it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.64 seconds
Image generated with private log at: D:\fooocus\outputs\2024-03-09\log.html
Generating and saving time: 36.19 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
  0%|          | 0/30 [00:00<?, ?it/s][Fooocus Model Management] Moving model(s) has taken 1.08 seconds
100%|██████████| 30/30 [00:09<00:00,  3.03it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.16 seconds
Image generated with private log at: D:\fooocus\outputs\2024-03-09\log.html
Generating and saving time: 12.84 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 285.19 seconds
[Fooocus Model Management] Moving model(s) has taken 2.19 seconds
```

### Additional information

the console says 258 sec but it takes more than that!

**Comment by mashb1t** [comment] 2024-03-09 18:27
Model size of anime model is the same as juggernaut (default model), even the default LoRA isn't loaded for anime.
Can't reproduce, runs as fast as default. Did you change the default_performance manually from speed to anything else?

**Comment by codezeros** [comment] 2024-03-10 10:00
> Model size of anime model is the same as juggernaut (default model), even the default LoRA isn't loaded for anime. Can't reproduce, runs as fast as default. Did you change the default_performance manually from speed to anything else?

nope just ran with default and quality it always go on waiting list

```
To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
```
after i gave prompt it go on process i check on cpu it started processing but still stuck for 2-4 min after it will start the process but this does not happen in default preset

**Comment by mashb1t** [comment] 2024-03-11 08:48
Still can't reproduce. Make sure you're using the same other arguments for both of the presets.
Closing as also no other person was able to confirm.
Feel free to still provide an update even when this issue is closed.

**Closed by mashb1t** 2024-03-11 08:48 UTC
Labels: bug, can't reproduce, feedback pending
