### ISSUE TITLE
[Bug]: Apps Crash

### ISSUE THREAD

**Issue by AgentHitmanFaris** [lllyasviel/Fooocus#2457] opened 2024-03-06 06:53 UTC
### Checklist

- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Everytime press generate the program suddenly crash and clossed connection
![image](https://github.com/lllyasviel/Fooocus/assets/81744011/8cf0e3a1-303c-4eff-950e-0a25bfae3a74)

### Steps to reproduce the problem

1. Enter Prompt then click generate
2. The connection closed and crash

### What should have happened?

Suppose the midel load and generate like normal

### What browsers do you use to access Fooocus?

Brave

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
Unet ADM Dimension

/fooocuss>pause
```

**Comment by DaVinchik** [comment] 2024-03-06 07:01
I have the same problem. But it appears immediately after startup. Windows 10 system, Edge browser. There is a problem with the new patch.
![image](https://github.com/lllyasviel/Fooocus/assets/48329167/8f02abcf-215f-47e9-b230-68a5686ef4c0)

**Comment by QuantumCrazy** [comment] 2024-03-06 11:12
I also noticed crashes after 2.2.0 release. There are memory issues with certain GPUs and ways to lesson the memory overhead if you read previous comments and bugs. However, what I did to 'fix' my problem was I just reverted to release 2.2.0-rc1. That for me is the most stable version and I am sticking with it until I thoroughly test future releases and I'm happy with them.

Try this version. Open bash and type:

cd Fooocus
git checkout 2.2.0-rc1
python3 launch.py

**Comment by mashb1t** [comment] 2024-03-06 17:15
=> see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#adm-2816-then-stuck, most likely an issue with your swap.

**Comment by AgentHitmanFaris** [comment] 2024-03-06 17:25
already done that the problem still available, haven't try to downgrade the version, b4 update works smoothly

**Comment by mashb1t** [comment] 2024-03-06 22:46
related / duplicate of https://github.com/lllyasviel/Fooocus/issues/2436. Maybe a driver update causes more resource need or you did start something in the background?

**Comment by AgentHitmanFaris** [comment] 2024-03-07 02:15
In older version Fooocus_win64_2-1-831 works fine for me

**Comment by DaVinchik** [comment] 2024-03-07 17:09
> => see https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#adm-2816-then-stuck, most likely an issue with your swap. @AgentHitmanFaris @DaVinchik please check this section and provide feedback.
I moved the paging file to another drive, turned off the automatic size, and manually set it to 40 gigabytes. It seems to have worked. Slower because it's an HDD and not an SSD.
It’s strange that before patch 2.2.0 everything worked fine and even very fast, considering the outdated video card (NVIDIA GTX 1050ti).

**Comment by mashb1t** [comment] 2024-03-07 21:56
@DaVinchik your system might have changed automated swap placement on an update

I'm still surprised that the new version might be causing crashes as no significant changes were in there concerning memory or resource allocation in general and extensive testing without issues was done before release, showing no indication of a potential increase in memory.

**Closed** 2024-03-07 21:58 UTC
Labels: bug, duplicate, question

**Comment by AgentHitmanFaris** [comment] 2024-03-08 11:06
I used on another pc the new version works fine...I have tried few solution and found one works, I tried for a few days and I will share back the solution

<details>
<summary>Spoiler warning</summary>

```
I just added a new script to check a few things
```
</details>

**Comment by Billsfan2** [comment] 2024-07-18 19:47
Hey I think mashb1t is right about the swap file possibly causing the issue. I was at my wits end yesterday and today with this issue after a video driver change when I stumbled on mashb1t's post here and remembered that I had decided to change swap file to "Fixed" rather than "Windows Managed". Changed it back, restarted P.C. And suddenly everything works again lol! Thanks mashb1t!
