### ISSUE TITLE
Drag-and-drop issue in Firefox

### ISSUE THREAD

**Issue by realmalikov** [lllyasviel/Fooocus#851] opened 2023-11-03 22:17 UTC
Please fix drag-and-drop (and CNTRL + V) of images from a browser tab into Foocus in Firefox. Drag-and-drop from Windows into your app works perfectly.

I have some hope as it works in 1111 and that shares the Gradio interface with Fooocus.

**Comment by lllyasviel** [comment] 2023-11-05 12:00
does a1111 drag work in firefox?

**Comment by realmalikov** [comment] 2023-11-06 03:49
> does a1111 drag work in firefox?

Yes. 

Around the time of the Windows 22H2 update, I was really surprised that I could hardly use drag-and-drop in Firefox. In the meantime, many websites have fixed this, but some, like replicate, unfortunately not.

**Comment by artofbeinghuman** [comment] 2023-12-05 13:28
drag and drop not working on 120.0 (64-bit), macos

**Comment by mashb1t** [comment] 2023-12-31 14:54
Superseded, closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1425

**Closed by mashb1t** 2023-12-31 14:54 UTC
