### ISSUE TITLE
Feature Request: Command line argument to disbale automatic model downloads

### ISSUE THREAD

**Issue by Blacksage81** [lllyasviel/Fooocus#1827] opened 2024-01-09 10:02 UTC
Hi, I am not new to the stable diffusion space and I heard so much about Fooocus and its wonderful Inpainting engine, and I would love to try it, but there is this one nagging problem. The insistence of the tool downloading Juggernaut v6 automatically before I can even try it. What's more, if the download fails the software is unable to generate, even if there is another XL checkpoint in the Fooocus model folder. Also my Fooocus config file partially generated (See Below) I have nearly 200gb of models on my PC already, so HDD space isn't an issue, I guess my issue is from the lack of control over a piece of software I have yet to even fully use. 

{
    "path_checkpoints": "C:\\Users\\HP\\stable-diffusion-webui\\models\\Stable-diffusion",
    "path_loras": "C:\\Users\\HP\\stable-diffusion-webui\\models\\Lora",
    "path_embeddings": "C:\Users\\HP\\stable-diffusion-webui\\embeddings",
    "path_vae_approx": "C:\\Users\\HP\\stable-diffusion-webui\\models\\VAE",
    "path_upscale_models": "C:\\Users\\HP\\stable-diffusion-webui\\models\\ESRGAN",
    "path_inpaint": "C:\\Users\\HP\\Focus\\Fooocus\\models\\inpaint",
    "path_controlnet": "C:\\Users\\HP\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models",
    "path_clip_vision": "C:\\Users\\HP\\ComfyUI_windows_portable\\ComfyUI\\models\\clip_vision",
    "path_fooocus_expansion": "C:\\Users\\HP\\Focus\\Fooocus\\models\\prompt_expansion\\fooocus_expansion",
    "path_outputs": "C:\\Users\\HP\\Focus\\Fooocus\\outputs"
}
<- the entirety of my Fooocus config file 
I can't even change the default model in the config file as I don't even have the option, so to my feature request. May we please have a command line ARG, or maybe a alternate .bat that disables the auto downloads?

**Comment by mashb1t** [comment] 2024-01-09 19:01
Feel free to use a preset with all your config settings and override the checkpoint download there.
You can refer to one of the existing presets (e.g. anime or realistic) and clone + modify one for your needs.
Starting Fooocus with a preset is described in the [README](https://github.com/lllyasviel/Fooocus) file, but easiest is if you also copy the run_anime.bat, rename it and modify the preset used in the file.

Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1564, hope this information helps!

**Closed** 2024-01-09 19:01 UTC
Labels: duplicate
