### ISSUE TITLE
Move image to trash button while viewing Fooocus Log 

### ISSUE THREAD

**Issue by barepixels** [lllyasviel/Fooocus#2350] opened 2024-02-25 04:36 UTC
while reviewing 100s of images, it would be nice to have a delete button next to the copy prompt button. this will save a lot of time purging unwanted images

**Comment by mashb1t** [comment] 2024-02-25 09:03
Sorry, but this is not possible as the history log is a static html file and you don't have access through JS to the file system of the computer. Only when using node.js or gradio this can be done, but the file is completely separate.
It would be a different story if the history log would be included in the webui.py in a tab, but this is separate by design.
Any other ideas how this could be solved?

**Comment by mashb1t** [comment] 2024-02-25 09:05
Oh, this is already an enhancement in https://github.com/lllyasviel/Fooocus/issues/1946. Closing as duplicate.

**Closed by mashb1t** 2024-02-25 09:05 UTC

**Comment by pablootero-cl** [comment] 2024-06-28 06:53
Can I suggest a button (clear history) that executes a python file:

`from` shutil import rmtree
`rmtree("outputs\*")`

I'm an amateur, I don't know if this helps anything
