### ISSUE TITLE
I hope to increase image upscaling by 4 times and import images in batches.

### ISSUE THREAD

**Issue by xiyangyang7788** [lllyasviel/Fooocus#2061] opened 2024-01-27 09:12 UTC
I hope to increase image upscaling by 4 times and import images in batches.

**Comment by mashb1t** [comment] 2024-01-27 14:25
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2 and https://github.com/lllyasviel/Fooocus/issues/1236

**Closed by mashb1t** 2024-01-27 14:25 UTC
