### ISSUE TITLE
AMD Error - Device type privateuseone is not supported for torch.Generator() api.

### ISSUE THREAD

**Issue by Atlas217** [lllyasviel/Fooocus#1095] opened 2023-12-01 05:43 UTC
**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

![image](https://github.com/lllyasviel/Fooocus/assets/72188545/0ea98670-9921-491b-9906-827d91df82e9)

**Comment by LichtBach** [comment] 2023-12-02 13:05
D:\Agency>.\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
Found existing installation: torch 2.0.0
Uninstalling torch-2.0.0:
  Successfully uninstalled torch-2.0.0
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "D:\Agency\python_embeded\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
  File "D:\Agency\python_embeded\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\Agency\python_embeded\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
  File "D:\Agency\python_embeded\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
  File "concurrent\futures\_base.py", line 451, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "D:\Agency\python_embeded\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
  File "D:\Agency\python_embeded\lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "shutil.py", line 750, in rmtree
  File "shutil.py", line 615, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
  File "shutil.py", line 618, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'D:\\Agency\\python_embeded\\Lib\\site-packages\\~~rch\\lib\\asmjit.dll'

D:\Agency>.\python_embeded\python.exe -m pip install torch-directml
Requirement already satisfied: torch-directml in d:\agency\python_embeded\lib\site-packages (0.2.0.dev230426)
Collecting torch==2.0.0 (from torch-directml)
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Requirement already satisfied: torchvision==0.15.1 in d:\agency\python_embeded\lib\site-packages (from torch-directml) (0.15.1)
Requirement already satisfied: filelock in d:\agency\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.12.2)
Requirement already satisfied: typing-extensions in d:\agency\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (4.7.1)
Requirement already satisfied: sympy in d:\agency\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (1.12)
Requirement already satisfied: networkx in d:\agency\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1)
Requirement already satisfied: jinja2 in d:\agency\python_embeded\lib\site-packages (from torch==2.0.0->torch-directml) (3.1.2)
Requirement already satisfied: numpy in d:\agency\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (1.23.5)
Requirement already satisfied: requests in d:\agency\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\agency\python_embeded\lib\site-packages (from torchvision==0.15.1->torch-directml) (9.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\agency\python_embeded\lib\site-packages (from jinja2->torch==2.0.0->torch-directml) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\agency\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\agency\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\agency\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\agency\python_embeded\lib\site-packages (from requests->torchvision==0.15.1->torch-directml) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in d:\agency\python_embeded\lib\site-packages (from sympy->torch==2.0.0->torch-directml) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: torch
  WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'D:\Agency\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed torch-2.0.0

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: D:\Agency\python_embeded\python.exe -m pip install --upgrade pip

D:\Agency>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 16297 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra keys {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: D:\Agency\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Agency\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\Agency\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Agency\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 4700088500423662016
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] old car, futuristic, dramatic light, gorgeous background, professional, highly detailed, sharp focus, cool color, perfect composition, symmetry, vivid colors, beautiful, emotional, cute, innocent, enhanced, glowing, peaceful, vibrant, intricate, brilliant, thought, cinematic, fine detail, clear, strong, artistic, complex, imposing, amazing, creative, great, atmosphere
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] old car, stunning sunny background, professional composition, vivid colors, elegant, dynamic detailed, very inspirational,, beautiful, intricate, highly detail, ambient, shiny, rich deep color, cinematic, complex, majestic, lucid, thought, full focus, epic, extremely fine, perfect, light shining, dramatic, symmetry, great, luxury,, winning, clear, focused
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 13.11 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Traceback (most recent call last):
  File "D:\Agency\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Agency\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Agency\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Agency\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\Agency\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Agency\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Agency\Fooocus\modules\default_pipeline.py", line 354, in process_diffusion
    modules.patch.BrownianTreeNoiseSamplerPatched.global_init(
  File "D:\Agency\Fooocus\modules\patch.py", line 173, in global_init
    BrownianTreeNoiseSamplerPatched.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
  File "D:\Agency\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\Agency\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\Agency\python_embeded\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "D:\Agency\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 540, in __init__
    W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
  File "D:\Agency\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 234, in _randn
    return _randn(size, self._top._dtype, self._top._device, seed)
  File "D:\Agency\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 32, in _randn
    generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
Total time: 39.93 seconds

**Comment by AlexPerni** [comment] 2023-12-02 23:57
I had the same issue. For me, the solution was to open the file
> python_embedded\Lib\site-packages\torchsde\_brownian\brownian_interval.py

And edit line 32 from
`generator = torch.Generator(device).manual_seed(int(seed))`
to
`generator = torch.Generator("cpu").manual_seed(int(seed))`

**Comment by LichtBach** [comment] 2023-12-03 13:14
![image](https://github.com/lllyasviel/Fooocus/assets/75524747/7352a926-ab52-4624-94bf-3b6b1c66bb24)
looks like this should I look for the code in another line?

**Comment by AlexPerni** [comment] 2023-12-03 20:29
Unfortunately I have the same. Seems to be a bug for many people, as there are a lot of issues reported on exactly this problem.

**Comment by TeeTeeHaa** [comment] 2023-12-04 20:08
> I had the same issue. For me, the solution was to open the file
> 
>python_embedded\Lib\site-packages\torchsde\_brownian\brownian_interval.py
> 
> And edit line 32 from `generator = torch.Generator(device).manual_seed(int(seed))` to `generator = torch.Generator("cpu").manual_seed(int(seed))`

This workaround worked for me, thanks. 👍 

AMD Radeon 6800 XT with 16 GB on Windows 11.

**Comment by mashb1t** [comment] 2023-12-30 17:22
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1304

As of https://github.com/lllyasviel/Fooocus/commit/8e62a72a63b30a3067d1a1bc3f8d226824bd9283 (latest Fooocus version 2.1.857) AMD with >= 8GB VRAM is now supported.
Please try with min. 8GB VRAM allocated.

**Closed by mashb1t** 2023-12-30 17:22 UTC
