### ISSUE TITLE
[Feature Request] Allow us to specify how much outpainting should occur?

### ISSUE THREAD

**Issue by vesper8** [lllyasviel/Fooocus#1235] opened 2023-12-06 18:27 UTC
Currently if I want to zoom out multiple times from a starting image I have to add the image to outpaint, do the outpainting, and then save the image, add it back, and rinse and repeat multiple times.

First of all it would be very nice to have a "Send to outpaint" option in the generated image.

I'd also like to be able to specify either the amount of pixels I wanted to be generated by outpaint, or the number of cycles I want to perform.. so I can start an outpainting job and come back 10 minutes later to a vastly enlarged image.

Thanks!

**Comment by mashb1t** [comment] 2023-12-29 15:38
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1245 (currently cleaning up issues in reverse order)

**Closed as not planned by mashb1t** 2023-12-29 15:38 UTC
Labels: duplicate
