### ISSUE TITLE
[Feature Request]: Support dual GPU

### ISSUE THREAD

**Issue by ITMEDIAVISION** [lllyasviel/Fooocus#3388] opened 2024-07-28 12:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Would it be possible to add a menu in advanced to toggle with GPU and also add dual GPU support? ( I have 2 RTX 3060's ) so would be nice to add 

### Proposed workflow

Advanced menu add toggles, menu option for GPU/CPU etc

**Comment by mashb1t** [comment] 2024-07-28 12:49
Duplicate of https://github.com/lllyasviel/Fooocus/issues/292, also see #2292

**Closed by mashb1t** 2024-07-28 12:49 UTC
Labels: enhancement, triage
