### ISSUE TITLE
Add hires fix[Feature Request]: 

### ISSUE THREAD

**Issue by ashrafbay** [lllyasviel/Fooocus#3143] opened 2024-06-12 23:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Hello. Please add an automatic hires fix so that it automatically upgrades every image created
This will make creating large amounts of high quality image possible
Thanks

### Proposed workflow

hires fix Check box
ratio upgrade
denoise ratio

**Comment by aquawaves** [comment] 2024-06-13 07:39
A duplicate of existing issue: https://github.com/lllyasviel/Fooocus/issues/3113

**Comment by ashrafbay** [comment] 2024-06-13 12:20
> A duplicate of existing issue: #3113

Sorry I didn't notice

**Closed** 2024-06-13 14:29 UTC
Labels: enhancement, triage

**Comment by mashb1t** [comment] 2024-06-20 00:57
implemented (at least in my fork), see https://github.com/lllyasviel/Fooocus/issues/3113#issuecomment-2179631376
