### ISSUE TITLE
Add a full prompt and negative prompt expansion to log.html for all styles

### ISSUE THREAD

**Issue by speadskater** [lllyasviel/Fooocus#1275] opened 2023-12-08 06:57 UTC
When an image is generated, the Log.html file gives a Fooocus V2 expansion, but does not give expansion for other styles, this makes replicatability difficult using other software.  Likewise, negative prompts added by styles are not added to the log, not even for Fooocus V2.

**Comment by speadskater** [comment] 2023-12-10 23:32
> Because it's an exclusive style blend, not just text links

Looking at the code, there is text associated with styles as well.

**Comment by mashb1t** [comment] 2023-12-31 00:25
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/955

**Closed by mashb1t** 2023-12-31 00:25 UTC
Labels: enhancement
