### ISSUE TITLE
When png with transparent background used for inpainting, Fooocus stuck at image processing

### ISSUE THREAD

**Issue by lanyusan** [lllyasviel/Fooocus#462] opened 2023-09-21 08:08 UTC
```
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
Fooocus Expansion engine loaded for cuda:0.
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Fooocus] Image processing ...
```
Image used for testing:

![medium](https://github.com/MoonRide303/Fooocus-MRE/assets/56706512/46ac8ea6-61ec-4688-ab3a-f684ff727a3c)

**Comment by lllyasviel** [comment] 2023-09-21 09:01
cannot reproduce problem - this is likely caused by python environment, please follow official installation guidelines

**Comment by MoonRide303** [comment] 2023-09-21 09:04
@lanyusan Works fine for me, too (in both vanilla and MRE):
![image](https://github.com/lllyasviel/Fooocus/assets/130458190/4fd3a92e-d8fc-41b6-a9ca-5b9104af4c3a)

**Comment by lanyusan** [comment] 2023-09-21 09:26
I tested it again. It works when mask is a small area on my PC too.

When I painted a large area, it got stuck. 

Below is the how I painted the mask. Fooocus got stuck. I was using MRE testing branch. 

![Screenshot from 2023-09-21 17-22-59](https://github.com/lllyasviel/Fooocus/assets/56706512/f53cd41e-7cc7-4cdb-a7e5-47dc644ac4d5)

**Comment by MoonRide303** [comment] 2023-09-21 09:38
@lanyusan I reproduced the problem in vanilla, too (with mask similar to yours).

**Comment by lllyasviel** [comment] 2023-09-21 10:05
i pushed a fix - hopefully resolved

**Comment by lllyasviel** [comment] 2023-09-21 10:11
but it seems png image has some leak problem and the background color seem to influence the process

**Comment by MoonRide303** [comment] 2023-09-21 10:28
@lllyasviel It looks like alpha is being replaced with black - which might cause troubles when trying to turn it into something else (like sunny beach in the background). But it's generic img2img problem, I think - images with white background are hard to turn into something else, too.

**Comment by MoonRide303** [comment] 2023-09-21 10:52
@lllyasviel A1111 has the similar problem, just the other way around - alpha gets replaced with white there, and then it's hard to turn it into something else (like late night cityscape).

Maybe latent blending area filled with alpha with completely random latent (as we do for initialising latent in txt2img mode) could do the trick?

**Comment by lanyusan** [comment] 2023-09-21 12:50
@lllyasviel @MoonRide303 

I understand the intended usecase of Fooocus. I was trying to push the boundary. 

There is a common case for commercial poster designers to place product images, for example cars, in different background. In many cases the product images are a transparent png files. If Fooocus can replace transparent background with background generated by prompts, it will give Fooocus a very strong commercial use case.

**Comment by lanyusan** [comment] 2023-09-21 23:35
@lllyasviel @MoonRide303 

Yes it works now. Just as you said, the transparent background was turned to pure black so when use inpaint to repaint whole background, the repainted background was very dark too.

Maybe transparent background should be randomized?

![image](https://github.com/lllyasviel/Fooocus/assets/56706512/eb032154-d9a7-4f90-9a11-d2f8b7d8bfb5)

**Closed** 2024-01-01 15:53 UTC
