### ISSUE TITLE
Cannot run on AMD GPU RX 580

### ISSUE THREAD

**Issue by swapnawebdev** [lllyasviel/Fooocus#1091] opened 2023-12-01 03:41 UTC
**Describe the problem**
AMD gpu rx 580 issue while running

**Full Console Log**
```
 generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
 ```

![image](https://github.com/lllyasviel/Fooocus/assets/148637423/edac8bf7-661a-4752-8bf4-3ebb669b2922)

**Comment by 66hzN125ping** [comment] 2023-12-02 18:37
My whole pc shuts down with rx580 4gb

**Comment by axnix** [comment] 2023-12-03 09:53
You can get rid of this error by this: https://github.com/lllyasviel/Fooocus/issues/624#issuecomment-1757327660
Maybe then you'll get another error "There is not enough GPU video memory available!" - Possible fix: https://github.com/lllyasviel/Fooocus/issues/624#issuecomment-1833571337
But as I already mentioned there, it didn't fixed it for me (win10,rx570 8gb)

**Comment by mashb1t** [comment] 2023-12-30 17:32
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1078

As of https://github.com/lllyasviel/Fooocus/commit/8e62a72a63b30a3067d1a1bc3f8d226824bd9283 (latest Fooocus version 2.1.857) AMD with >= 8GB VRAM is now supported.
Please try with min. 8GB VRAM allocated.

**Closed by mashb1t** 2023-12-30 17:32 UTC
