### ISSUE TITLE
[Bug]: error when creating about 7 or more sequential images using the new updated version of fooocus

### ISSUE THREAD

**Issue by MoacirEduardo** [lllyasviel/Fooocus#2447] opened 2024-03-05 06:49 UTC
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

in this new update if you start to do a lot of generations in sequence, more than 5 at least, is common for the app to lose the connection with the web interface and show in the console an error. I am not a coder expert so I will show the sum up of GPT-4 about the possible problem: 
The application encountered a `FileNotFoundError` while executing a task involving the Gradio library. The error occurred when trying to open an image file that was not found at the specified path. This issue suggests that the file might have been moved, deleted, or the path might have been incorrectly specified in the code. The error points to an inability to locate the file '...\\outputs\\2024-03-05\\2024-03-05_03-31-47_6970.png', indicating a potential problem with file handling or path configuration in the application.

Note: I have reinstalled fooocus 3 times, and found the same problem.

### Steps to reproduce the problem

Generate a lot of images in a single time.

### What should have happened?

Something related to file management in the new update of fooocus

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

windows 11

### Console logs

```Shell
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
Traceback (most recent call last):
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1326, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 460, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\components\gallery.py", line 203, in postprocess
    file_path = self.make_temp_copy_if_needed(img)
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\desua\\OneDrive\\Área de Trabalho\\Fooocus\\Fooocus\\outputs\\2024-03-05\\2024-03-05_03-31-47_6970.png'
```

### Additional information

I love this app please keep doing the great job you are doing guys. Thanks.
![Captura de tela 2024-03-05 034834](https://github.com/lllyasviel/Fooocus/assets/99088947/5990731c-510a-4e84-9eeb-bbe727a3c0dd)

**Comment by mashb1t** [comment] 2024-03-05 07:23
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/2445

**Closed by mashb1t** 2024-03-05 07:23 UTC
Labels: bug, triage
