### ISSUE TITLE
Input image checkbox does nothing

### ISSUE THREAD

**Issue by kajmus** [lllyasviel/Fooocus#1633] opened 2023-12-28 14:55 UTC
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**

Input image checkbox does nothing. Advanced checkbox works fine, program generates images correctly.

Installed on Windows 10 PRO 22H2

**Full Console Log**

Error from firefox web dev tool:

```
Uncaught (in promise) ReferenceError: viewer_to_bottom is not defined
    result Blocks-b3881047.js line 44 > AsyncFunction:3
    anonymous Blocks-b3881047.js line 44 > AsyncFunction:3
    we Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    dispatch Blocks-b3881047.js:12
    N InteractiveCheckbox.svelte:38
    wc lifecycle.js:105
    wc lifecycle.js:104
    l Checkbox.svelte:17
    update Checkbox.svelte:25
    Zi scheduler.js:115
    Bo scheduler.js:79
    promise callback*To scheduler.js:20
    ea Component.js:79
    ctx Component.js:127
    v Blocks-b3881047.js:39
    s Blocks-b3881047.js:39
    ctx Component.js:126
    S InteractiveCheckbox.svelte:25
    k InteractiveCheckbox.svelte:31
    ctx Component.js:126
    g Checkbox.svelte:32
Blocks-b3881047.js line 44 > AsyncFunction:3:35
```

```
Uncaught (in promise) ReferenceError: viewer_to_top is not defined
    result Blocks-b3881047.js line 44 > AsyncFunction:3
    anonymous Blocks-b3881047.js line 44 > AsyncFunction:3
    we Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    t Blocks-b3881047.js:45
    dispatch Blocks-b3881047.js:12
    N InteractiveCheckbox.svelte:38
    wc lifecycle.js:105
    wc lifecycle.js:104
    l Checkbox.svelte:17
    update Checkbox.svelte:25
    Zi scheduler.js:115
    Bo scheduler.js:79
    promise callback*To scheduler.js:20
    ea Component.js:79
    ctx Component.js:127
    v Blocks-b3881047.js:39
    s Blocks-b3881047.js:39
    ctx Component.js:126
    S InteractiveCheckbox.svelte:25
    k InteractiveCheckbox.svelte:31
    ctx Component.js:126
    g Checkbox.svelte:32
Blocks-b3881047.js line 44 > AsyncFunction:3:85
```

Error from Chrome web dev tool in a file:
[localhost-1703771940314.log](https://github.com/lllyasviel/Fooocus/files/13787116/localhost-1703771940314.log)

**Comment by mashb1t** [comment] 2023-12-28 16:10
Strange, works fine for other users. Can you please provide the full Fooocus terminal output?

**Comment by kajmus** [comment] 2023-12-28 17:01
Adblock is off and it still doesn't work. JavaScript should be working too.

looking at the network tab i have found script loading errors:

> Wczytanie się nie powiodło dla elementu „script” ze źródłem „http://127.0.0.1:7865/file=T:/##money\project_ai\Fooocus\javascript\script.js?1703606122.0998895”. 127.0.0.1:7865:56:112

(which translates to: Script element could not be loaded, using source...)
The slashes in the path look kinda weird. Full output is in the attached file.

[console-export-2023-12-28_17-52-13.txt](https://github.com/lllyasviel/Fooocus/files/13788186/console-export-2023-12-28_17-52-13.txt)

Fooocus terminal output:
![obraz](https://github.com/lllyasviel/Fooocus/assets/144721087/69d138e5-c7cf-42cc-9e6d-3b717cbdcf85)

**Comment by mashb1t** [comment] 2023-12-28 18:35
just saw that this is a duplicate of https://github.com/lllyasviel/Fooocus/issues/1582

**Closed by mashb1t** 2023-12-28 18:35 UTC

**Comment by mashb1t** [comment] 2023-12-29 01:41
Solution (workaround until fixed): see https://github.com/lllyasviel/Fooocus/issues/1379 (https://github.com/lllyasviel/Fooocus/issues/1379#issuecomment-1859847504)
