### ISSUE TITLE
PC turns off after starting image generation

### ISSUE THREAD

**Issue by harrypango** [lllyasviel/Fooocus#1810] opened 2024-01-08 16:07 UTC
I am trying to generate images on my other PC and it just shuts down right after staring he first image generation (after 1st sample). I can't know for sure which error it is because it turns off. 
My PC specs:
64GB RAM
AMD Ryzen 9 3950X
AMD Radeon RX 5700 XT

Has anyone else been facing this error?

**Comment by mashb1t** [comment] 2024-01-08 16:18
Actually yes, duplicate of https://github.com/lllyasviel/Fooocus/issues/1690 where probably one solution is to buy a new PSU powerful enough to supply and sustain your PC (expecially GPU) with sufficient power. But could be a few more things. Please check it out!

**Closed** 2024-01-08 16:18 UTC
Labels: duplicate
