### ISSUE TITLE
Запуск на intel

### ISSUE THREAD

**Issue by den47999** [lllyasviel/Fooocus#1776] opened 2024-01-07 01:09 UTC
подскажите как можно запустить  на видеокарте intel? при запросе выходит ошибка.

**Comment by mashb1t** [comment] 2024-01-07 02:12
Sorry to say, but Fooocus doesn't currently offer support for Intel GPUs of any kind.
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1107, also see https://github.com/lllyasviel/Fooocus/issues/1470

**Closed by mashb1t** 2024-01-07 02:12 UTC
