### ISSUE TITLE
Moving models to GPU memory on Linux is slower than on Windows（not first generate）

### ISSUE THREAD

**Issue by ImmNaruto** [lllyasviel/Fooocus#1021] opened 2023-11-24 03:30 UTC
### **Describe the problem**
As the title suggests, moving models to the GPU memory on CentOS is slower than on Windows, even though both are SSD hard drives and have identical environment configurations and code versions (2.1.823). I would like to ask if there is a bug in the model management part on Linux.

Additionally, I tested an older version of Fooocus (2.1.679) on a CentOS server environment with a mechanical hard drive（HDD）, and the loading speed was normal and consistent with Windows.

Please refer to the highlighted sections in the log for a speed comparison,Thanks.

### **In Windows：**
Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 8676532708116039652
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] cat, cinematic, epic light, crisp detail, extremely detailed, clear, symmetry, great composition, dynamic, elegant, innocent, cute, confident, passionate, color spread, professional, best, creative, positive, artistic, vibrant, aesthetic, beautiful, dramatic, engaging, perfect, focused, pretty, attractive, illuminated, enhanced, advanced, deep background, futuristic, stunning
[Fooocus] Encoding positive #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 0.93 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970141649246216, sigma_max = 14.614640235900879
Requested to load SDXL
Loading 1 new model
**[Fooocus Model Management] Moving model(s) has taken 1.58 seconds**
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  4.56it/s]
Generating and saving time: 4.28 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.40 seconds
Total time: 6.09 seconds

### **In linux（centos）：**
Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 2071215352743159436
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] Philosophy,Romantic,It's nothing, romantic, full, frank, intricate, elegant, highly detailed, dramatic light, illuminated, incredible composition, sharp focus, cinematic, extremely beautiful, stunning, very inspirational, inspiring, creative, winning new, color, fine detail, baked colors, enhanced, clear quality, bright, futuristic, epic, background, inspired
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.17 seconds
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 1.22 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970141649246216, sigma_max = 14.614640235900879
Requested to load SDXL
Loading 1 new model
**[Fooocus Model Management] Moving model(s) has taken 6.43 seconds**
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  4.36it/s]
Generating and saving time: 8.91 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 1.97 seconds

**Comment by mashb1t** [comment] 2024-01-12 20:59
Quite a few things changed since you reported the issue. Please check again with the latest vesion of Fooocus and feel free to close the issue if this is still relevant.

**Comment by mashb1t** [comment] 2024-01-18 22:43
@ImmNaruto can you confirm that this behavior is still reproducible with the latest version of Fooocus (2.1.862)?

**Comment by ImmNaruto** [comment] 2024-01-23 05:37
@mashb1t Sure, I'll give it a try later.

**Comment by mashb1t** [comment] 2024-02-01 19:06
Closing as stale

**Closed by mashb1t** 2024-02-01 19:06 UTC
Labels: question

**Comment by ImmNaruto** [comment] 2024-04-07 03:32
@mashb1t The issue has been resolved. Thank you very much.
