### ISSUE TITLE
Fooocus for Stable Swarm or MultiGPU?

### ISSUE THREAD

**Issue by sfingali** [lllyasviel/Fooocus#367] opened 2023-09-13 22:24 UTC
This is such a fantastic utility. I really like using both my 3090s in Stable Swarm via a Comfy UI interface. Fooocus integrated into this or offering simultaneous generation would be a game changer.

**Comment by mashb1t** [comment] 2024-01-01 16:14
Duplicate of https://github.com/lllyasviel/Fooocus/issues/292. StableSwarm integration is not planned for now.

**Closed by mashb1t** 2024-01-01 16:14 UTC
