### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by Filip78958** [lllyasviel/Fooocus#1106] opened 2023-12-01 12:58 UTC
it runs for 17 second and then stop and in administrator is mesage RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
Total time: 17.03 seconds

**Comment by vivekratr** [comment] 2023-12-01 18:00
same error please help

**Comment by Chandima1990** [comment] 2023-12-02 18:56
There is no error for me but it stops after few seconds

**Comment by Chandima1990** [comment] 2023-12-05 20:06
It turns out the problem for me was the RAM capacity. After closing down the browser, which was eating half of the RAM, this worked for me. But it's super slow, and from time to time it breaks.

**Comment by mashb1t** [comment] 2023-12-30 17:15
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1304

**Closed by mashb1t** 2023-12-30 17:15 UTC
