### ISSUE TITLE
A good  and importent idea! InvokeAI unified canvas

### ISSUE THREAD

**Issue by ycz8681** [lllyasviel/Fooocus#1805] opened 2024-01-08 08:57 UTC
偶尔接触了InvokeAI,它的统一画布功能实在是好用,就跟用Photoshop的创尘式功能一样,如果能够吸收过来,那真的是巨大的惊喜!

I came into contact with InvokeAI by chance, and its unified canvas function is really easy to use, just like using Generative fill in photoshop If fooocus can absorb it, it will be a huge surprise!

**Comment by mashb1t** [comment] 2024-01-08 09:39
Thank you for the proposal. This should be a duplicate of https://github.com/lllyasviel/Fooocus/issues/996, please confirm and close the issue if it is. Much appreciated.

**Closed** 2024-01-08 16:11 UTC
Labels: duplicate
