### ISSUE TITLE
Error when generating

### ISSUE THREAD

**Issue by Riccky39** [lllyasviel/Fooocus#1834] opened 2024-01-09 13:02 UTC
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I have done all neccesary to download the software, but when I try to generate anything it instantly gives me error.

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by Riccky39** [comment] 2024-01-09 13:13
<img width="1128" alt="Screenshot 2024-01-09 140422" src="https://github.com/lllyasviel/Fooocus/assets/127784922/971887cf-1d11-460e-a0b8-77eb9a3346ff">

**Comment by mashb1t** [comment] 2024-01-09 13:15
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1835

**Closed** 2024-01-09 13:15 UTC
