### ISSUE TITLE
[Bug]:  Re: some parameters in "config.txt" ignored on Fooocus startup in V2.3.0 #2566

### ISSUE THREAD

**Issue by DavidDragonsage** [lllyasviel/Fooocus#2609] opened 2024-03-23 00:10 UTC
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Following the update to 2.3.0, the only fault remaining for me is that "default_image_number" resets to 1 every time I change presets. My setting in config.txt is "default_image_number": 5,

I tried adding "default_image_number": 5, to my custom presets but that did not help.

For trouble-shooting purposes, I just did a clean installation of Fooocus, so the Image Number started at 2. But whenever I change to another preset, the Image Number resets to 1. The problem remains the same.

### Steps to reproduce the problem

1) Start Fooocus
2) Change the Image Number to any value, other than 1
3) Switch to a different preset
4) The Image Number will have reset to 1

### What should have happened?

The image number should stay the same, no matter which preset you use.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
C:\stable-diffusion-webui>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
Repository not found at C:\stable-diffusion-webui\Fooocus
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.0
[Cleanup] Attempting to delete content of temp dir C:\Users\buyer\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to C:\stable-diffusion-webui\Fooocus\models\vae_approx\xlvaeapp.pth

100%|███████████████████████████████████████████████████████████████████████████████| 209k/209k [00:00<00:00, 3.65MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt" to C:\stable-diffusion-webui\Fooocus\models\vae_approx\vaeapp_sd15.pth

100%|███████████████████████████████████████████████████████████████████████████████| 209k/209k [00:00<00:00, 4.17MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xl-to-v1_interposer-v3.1.safetensors" to C:\stable-diffusion-webui\Fooocus\models\vae_approx\xl-to-v1_interposer-v3.1.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 6.25M/6.25M [00:00<00:00, 14.3MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to C:\stable-diffusion-webui\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin

100%|███████████████████████████████████████████████████████████████████████████████| 335M/335M [00:16<00:00, 21.2MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to C:\stable-diffusion-webui\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 6.62G/6.62G [05:54<00:00, 20.0MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors" to C:\stable-diffusion-webui\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 47.3M/47.3M [00:02<00:00, 21.2MB/s]
Total VRAM 4096 MB, total RAM 28589 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\stable-diffusion-webui\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\stable-diffusion-webui\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [C:\stable-diffusion-webui\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\stable-diffusion-webui\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Started worker with PID 1476
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
Loaded preset: C:\stable-diffusion-webui\Fooocus\presets\realistic.json
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/realisticStockPhoto_v20.safetensors" to C:\stable-diffusion-webui\Fooocus\models\checkpoints\realisticStockPhoto_v20.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 6.46G/6.46G [05:28<00:00, 21.1MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors" to C:\stable-diffusion-webui\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors

100%|███████████████████████████████████████████████████████████████████████████████| 222M/222M [00:10<00:00, 21.6MB/s]
Loaded preset: C:\stable-diffusion-webui\Fooocus\presets\default.json
Loaded preset: C:\stable-diffusion-webui\Fooocus\presets\lcm.json
Loaded preset: C:\stable-diffusion-webui\Fooocus\presets\default.json
Loaded preset: C:\stable-diffusion-webui\Fooocus\presets\realistic.json
```

### Additional information

I think this one just got overlooked in the thread:
https://github.com/lllyasviel/Fooocus/issues/2566

**Comment by mashb1t** [comment] 2024-03-23 09:08
This is not necessarily a bug but an intended feature, at least it was until preset selection has been made available in the UI. When starting the presets with console arg, this parameter is set as default.
I can see that this can cause unexpected behavior now and we'll have to come up with a solution suiting both console arg and UI preset selection.

**Comment by mashb1t** [comment] 2024-03-23 09:38
One addition: as metadata import, history log import and preset switch use the same functionality this adjustment would have a bigger impact than the one described in this issue. I'd see it rather as a won't fix.

**Comment by mashb1t** [comment] 2024-03-23 11:49
@DavidDragonsage fixed & implemented

**Closed** 2024-03-23 11:49 UTC
Labels: bug

**Comment by DavidDragonsage** [comment] 2024-03-23 14:58
Wonderful! I just started Fooocus and noticed it working as expected. I've been doing a lot of model testing lately using preset switching and prompt arrays requiring a size of 2. That resetting to 1 problem was driving me crazy!

Yes, it wouldn't have been a problem until the ability to switch presets within Fooocus was introduced in version 2.3.

Thanks so much!
