### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RanjithGadde447** [lllyasviel/Fooocus#2654] opened 2024-03-27 17:06 UTC
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

am using using foocus from 3 months ia m using it from 2.18 version 
currently am using 2.3.0     launching web ui taking long time  its was not in the prrevious versions   it running fast until cleanup successfull   then it stucking for long time i mean about 1 or two minutes    in the the previous versions when i click run realistic bat it open within 10 seconds      noew launching time increased to 2 min 
![Screenshot 2024-03-27 223002](https://github.com/lllyasviel/Fooocus/assets/152670547/a73ae6c2-8090-4b0d-bc7c-286f11275559)

### Steps to reproduce the problem

install on windows mechine and run the  run realistic bat and check command 
![Screenshot 2024-03-27 223002](https://github.com/lllyasviel/Fooocus/assets/152670547/b5ab8a9f-bea0-4b05-b977-8c99e0f86945)

### What should have happened?

 it running fast until cleanup successfull   then it stucking for long time i mean about 1 or two minutes    in the the previous versions when i click run realistic bat it open within 10 seconds      noew launching time increased to 2 min 
 
 it should launch within 10-20 sec atleast 

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

windows 11 pro

### Console logs

```Shell
its running upto cleanup successfull then its stucking for 1-2 min on local mechine in previous versions it started imediately
```

### Additional information

yes i have updated my gpu driver on 19th march

**Comment by mashb1t** [comment] 2024-03-29 19:00
Can't reproduce, have you checked the resource allocaton in task manager? Some changes of yours are also preventing the update to 2.3.1, ehich includes various Bugfixes. Make sure to stash)reset your local changes and update to 2.3.1 first and provide feedback after doing so.
Closing this issue for now, awaiting your feedback.

**Closed by mashb1t** 2024-03-29 19:00 UTC
Labels: bug, triage
