### ISSUE TITLE
There are so many styles...

### ISSUE THREAD

**Issue by StepHaze** [lllyasviel/Fooocus#2037] opened 2024-01-25 03:43 UTC
There are so many styles in Fooocus. Is there a tutorial or list of images (examples) created by these styles, so we could quickly choose the style?

Thanks!

**Comment by eddyizm** [comment] 2024-01-25 04:39
You can hover over the style to get a preview using a cat if you are on the latest version. 
There is also this [sample gallery](https://github.com/lllyasviel/Fooocus/discussions/143) that @Elathi created.

**Comment by f0n51** [comment] 2024-01-25 07:23
Additionally, there are a few pull requests in the pipeline concerning the style 'window'. AFAIK there will be better sorting and grouping.

**Comment by mashb1t** [comment] 2024-01-25 10:48
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1770. There also is an enhancement issue aready for making it a select, but we'll have to see about that.

**Closed by mashb1t** 2024-01-25 10:48 UTC
