### ISSUE TITLE
Is there any option for "Tiling" ? How to generate seamless patterns in Fooocus?

### ISSUE THREAD

**Issue by simartem** [lllyasviel/Fooocus#1353] opened 2023-12-12 15:59 UTC
Hello, friends! Is there any option (maybe something like "Tiling" checkbox or like that) or at least possibility to generate seamless patterns in Fooocus? I've tried several tokens, but they seem to be working not as good as expected.

_Originally posted by @Pixeldud3 in https://github.com/lllyasviel/Fooocus/discussions/117#discussioncomment-7406873_

Is there any workaround for this ability ? Generating seamless tiles would be great in Fooocus!

**Comment by mashb1t** [comment] 2023-12-31 15:59
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/665

**Closed by mashb1t** 2023-12-31 15:59 UTC
Labels: enhancement
