### ISSUE TITLE
lllyasviel/Fooocus can i use colab free without the need to install everything all over again every time? everytime  i need to install all models or i can just run !pip install pygit2==1.12.2 %cd /content !git clone https://github.com/lllyasviel/Fooocus.git %cd /content/Fooocus !python entry_with_update.py --share

### ISSUE THREAD

**Issue by Amit30swgoh** [lllyasviel/Fooocus#1586] opened 2023-12-25 15:20 UTC
!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share

**Comment by mashb1t** [comment] 2023-12-25 18:40
duplicate of https://github.com/lllyasviel/Fooocus/issues/1584

**Closed** 2023-12-27 14:23 UTC
