### ISSUE TITLE
Image Maximum Size Limit Option and Batch Mode -Feature Request

### ISSUE THREAD

**Issue by drdancm** [lllyasviel/Fooocus#1853] opened 2024-01-10 09:13 UTC
**Is your feature request related to a problem? Please describe.**

When working with a folder full of images where one side is greater than about 2000 pixels, processing may fail due to Video Card VRAM or some other limitations. The only current solution is to resize all of the images with an external graphics program. If the all of the images are the same size, this works well, if they are not, then manual scaling is often, though not always) the only solution. I am aware that Fooocus can scale images, but it does them one at a time, right?

In any case it is an extra step that one must take prior to using the Excellent Fooocus.

In Automatic 1111, when working with img2img etc. there are two setting for the Scaling feature. One for setting x and y separately, and another for multiplying both x and y at once allowing both + and - values.  In the Extras Tab, you are limited to + values (this is very bad!). 
Once again this requires extra manual work unless all of the images in a folder are the same size, and when using the Extras Tab (for Reactor for example), image sizes above  your max value makes it unusable. Once again forcing you to use an external graphics program to downscale before you can run img2img etc.

I don't see why A1111 has not already built in an option to scale the input images automatically, so that the maximum size is  limited to a **user set value** such as 1280, or 1600, or 2000 pixels (or specific values that work best for SDXL)).  

**Describe the idea you'd like**

1) Since Fooocus makes so many of the operations so much easier than A1111, it would be great to have Fooocus have this autoscaling feature with a user set maximum pixel size for the longest side of an image.

2) In addition, would it be possible to also have a batch mode allowing the user to browse for both an input and and output folder.

Thanks !

**Comment by mashb1t** [comment] 2024-01-10 12:55
@drdancm great issue description, but duplicate of https://github.com/lllyasviel/Fooocus/issues/1236.
Thank you for your effort, will reference the proposal in the other issue again.

**Closed by mashb1t** 2024-01-10 12:55 UTC
Labels: duplicate, good first issue
