### ISSUE TITLE
Не устанавливается на Дебиан (это Линукс) ни одним из трёх способов.

### ISSUE THREAD

**Issue by tsvigo** [lllyasviel/Fooocus#1865] opened 2024-01-11 03:14 UTC
### Discussed in https://github.com/lllyasviel/Fooocus/discussions/1864

<div type='discussions-op-text'>

<sup>Originally posted by **tsvigo** January 11, 2024</sup>
ModuleNotFoundError: No module named 'pygit2'</div>

**Comment by mashb1t** [comment] 2024-01-11 11:14
There just was a similar case, make sure you're using not your system git but the venv (if this is the case) and make sure to use python3 and not python (if applicable).

**Comment by mashb1t** [comment] 2024-01-14 10:52
Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1875

**Closed by mashb1t** 2024-01-14 10:52 UTC
Labels: question
