### ISSUE TITLE
Unable to update to the latest version

### ISSUE THREAD

**Issue by 211169887** [lllyasviel/Fooocus#2106] opened 2024-01-30 12:41 UTC
Below is the code in the backend, it can't get the latest version due to operation timeout

E:\fooocus2.1>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
failed to send request: 操作超时

Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Failed to load config key: {"path_checkpoints": "D:\\fooocus2.1\\Fooocus\\models\\checkpoints"} is invalid or does not exist; will use {"path_checkpoints": "../models/checkpoints/"} instead.
Failed to load config key: {"path_loras": "D:\\fooocus2.1\\Fooocus\\models\\loras"} is invalid or does not exist; will use {"path_loras": "../models/loras/"} instead.
Failed to load config key: {"path_embeddings": "D:\\fooocus2.1\\Fooocus\\models\\embeddings"} is invalid or does not exist; will use {"path_embeddings": "../models/embeddings/"} instead.
Failed to load config key: {"path_vae_approx": "D:\\fooocus2.1\\Fooocus\\models\\vae_approx"} is invalid or does not exist; will use {"path_vae_approx": "../models/vae_approx/"} instead.
Failed to load config key: {"path_upscale_models": "D:\\fooocus2.1\\Fooocus\\models\\upscale_models"} is invalid or does not exist; will use {"path_upscale_models": "../models/upscale_models/"} instead.
Failed to load config key: {"path_inpaint": "D:\\fooocus2.1\\Fooocus\\models\\inpaint"} is invalid or does not exist; will use {"path_inpaint": "../models/inpaint/"} instead.
Failed to load config key: {"path_controlnet": "D:\\fooocus2.1\\Fooocus\\models\\controlnet"} is invalid or does not exist; will use {"path_controlnet": "../models/controlnet/"} instead.
Failed to load config key: {"path_clip_vision": "D:\\fooocus2.1\\Fooocus\\models\\clip_vision"} is invalid or does not exist; will use {"path_clip_vision": "../models/clip_vision/"} instead.
Failed to load config key: {"path_fooocus_expansion": "D:\\fooocus2.1\\Fooocus\\models\\prompt_expansion\\fooocus_expansion"} is invalid or does not exist; will use {"path_fooocus_expansion": "../models/prompt_expansion/fooocus_expansion"} instead.
Failed to load config key: {"path_outputs": "D:\\fooocus2.1\\Fooocus\\outputs"} is invalid or does not exist; will use {"path_outputs": "../outputs/"} instead.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865
Total VRAM 12287 MB, total RAM 65484 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention

To create a public link, set `share=True` in `launch()`.
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: E:\fooocus2.1\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [E:\fooocus2.1\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [E:\fooocus2.1\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [E:\fooocus2.1\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models

**Comment by 211169887** [comment] 2024-01-30 13:23
This is a windows specification.

版本	Windows 10 专业工作站版
版本号	22H2
安装日期	‎2023/‎9/‎14
操作系统内部版本	19045.3803
体验	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by 211169887** [comment] 2024-01-30 13:24
Previous versions have been updating fine, but not since this 2.1.862!

**Comment by mashb1t** [comment] 2024-01-30 20:34
Duplicate of https://github.com/lllyasviel/Fooocus/issues/2101.
Please make sure you can git pull.

**Closed by mashb1t** 2024-01-30 20:34 UTC
