### ISSUE TITLE
[FEATURE REQUEST] Activation text for LoRAs

### ISSUE THREAD

**Issue by pralium444** [lllyasviel/Fooocus#1026] opened 2023-11-24 11:54 UTC
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the idea you'd like**
A simple field appears when i select the lora, i fill the field with the activation text, it stores it somewhere...and everytime i choose this lora, the activation text is automatically pasted in positive prompt

nice UI ! thanks for making it
Love

**Comment by mashb1t** [comment] 2023-12-30 19:38
Duplicate of https://github.com/lllyasviel/Fooocus/issues/1476, continuing there.

**Closed by mashb1t** 2023-12-30 19:38 UTC
Labels: enhancement
