### ISSUE TITLE
Cannot drag & drop a created image

### ISSUE THREAD

**Issue by GoodCharles** [lllyasviel/Fooocus#1540] opened 2023-12-21 11:47 UTC
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I wish to further manipulate the image but dragging and dropping does nothing. I am using Firefox

**Full Console Log**
{
"Prompt": "A humanoid bio-mechanic android standing in a highly futuristic and rundown hallway of a derelict spaceship. In the style of H.R. Giger with a mixture of futuristic industrial look of Chris Foss and Peter Elson",
"Negative Prompt": "",
"Fooocus V2 Expansion": "A humanoid bio-mechanic android standing in a highly futuristic and rundown hallway of a derelict spaceship. In the style of H.R. Giger with a mixture of futuristic industrial look of Chris Foss and Peter Elson, vibrant colors, open background, cinematic color, dynamic dramatic atmosphere, full detailed, creative, positive, romantic, cute, fine detail, pretty",
"Styles": "['Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp', 'Misc Horror', 'Misc Macabre']",
"Performance": "Quality",
"Resolution": "(1152, 896)",
"Sharpness": 2,
"Guidance Scale": 4,
"ADM Guidance": "(1.5, 0.8, 0.3)",
"Base Model": "juggernautXL_version6Rundiffusion.safetensors",
"Refiner Model": "None",
"Refiner Switch": 0.5,
"Sampler": "dpmpp_2m_sde_gpu",
"Scheduler": "karras",
"Seed": 7142657090438643968,
"LoRA 1": "sd_xl_offset_example-lora_1.0.safetensors : 0.1",
"Version": "v2.1.854"
}

**Comment by Kralg** [comment] 2023-12-22 11:25
I am also unable to drag and drop. I am using firefox on windows.

**Comment by mashb1t** [comment] 2023-12-22 20:40
duplicate of https://github.com/lllyasviel/Fooocus/issues/1425

**Closed** 2023-12-28 18:59 UTC
Labels: duplicate

**Comment by BassAzayda** [comment] 2024-07-23 04:28
i made a bookmarklet here:

```
javascript:(function(){let draggedImageData=null;let currentDropZone=null;function handleDragStart(event){const img=event.target;draggedImageData=img.src;}function handleDragOver(event){event.preventDefault();currentDropZone=event.currentTarget;}function handleDrop(event){event.preventDefault();if(!draggedImageData||!currentDropZone){return;}const dropZone=currentDropZone.closest('.image-container > div:first-child');if(!dropZone){return;}fetch(draggedImageData).then(res=> res.blob()).then(blob=>{const file=new File([blob],"dragged-image.png",{type:blob.type});const dummyFileList={0:file,length:1,item:index=> dummyFileList[index]};let dropEvent=new Event('drop',{bubbles:true});Object.defineProperty(dropEvent,'dataTransfer',{value:{files:dummyFileList}});dropZone.dispatchEvent(dropEvent);console.log('Drop event triggered successfully for drop zone');}).catch(error=> console.error('Error creating File from image:',error));draggedImageData=null;currentDropZone=null;}function addEventListeners(){document.querySelectorAll('.thumbnail-item img').forEach(img=>{img.addEventListener('dragstart',handleDragStart);img.addEventListener('dragend',handleDrop);});document.querySelectorAll('.image-container > div:first-child').forEach(dropZone=>{dropZone.addEventListener('dragover',handleDragOver);dropZone.addEventListener('drop',handleDrop);});}addEventListeners();const observer=new MutationObserver(mutationsList=>{for(let mutation of mutationsList){if(mutation.type==='childList'){mutation.addedNodes.forEach(node=>{if(node.matches&&node.matches('.thumbnail-item img')){addEventListeners();}});}}});observer.observe(document.body,{childList:true,subtree:true});console.log('Automatic image drop trigger is now active');})();

```
