### ISSUE TITLE
Support Multiple GPUs For Parallel Generating

### ISSUE THREAD

**Issue by thiner** [lllyasviel/Fooocus#1034] opened 2023-11-25 12:19 UTC
**Is your feature request related to a problem? Please describe.**
I tried to increase the throughput of Fooocus by adding multiple GPUs. I added two GPUs for test, and set the system environment argument `CUDA_VISIBLE_DEVICES=0,1` before launch Fooocus. I found that only one of the GPUs get used in process. The Fooocus seems doesn't support parallel generating. I checked Fooocus code, found below snippet:
```python
parser.add_argument("--cuda-device", type=int, default=None, metavar="DEVICE_ID", help="Set the id of the cuda device this instance will use.")
```
This line of code seems prove that only one cuda device is used by design.

**Describe the idea you'd like**
Please consider support multiple GPUs.

**Comment by mashb1t** [comment] 2023-12-30 19:32
Duplicate of https://github.com/lllyasviel/Fooocus/issues/292, still valid feature.

**Closed by mashb1t** 2023-12-30 19:32 UTC
