### ISSUE TITLE
[Bug]: gradio.exceptions.Error: 'Unsupported image type in input'

### ISSUE THREAD

**Issue by connerlarsen** [lllyasviel/Fooocus#3501] opened 2024-08-11 18:00 UTC
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

gradio.exceptions.Error: 'Unsupported image type in input'

### Steps to reproduce the problem

gradio.exceptions.Error: 'Unsupported image type in input'

### What should have happened?

gradio.exceptions.Error: 'Unsupported image type in input'

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

colab

### Console logs

```Shell
gradio.exceptions.Error: 'Unsupported image type in input'
```

### Additional information

gradio.exceptions.Error: 'Unsupported image type in input'

**Comment by mashb1t** [comment] 2024-08-11 20:56
Duplicate of https://github.com/lllyasviel/Fooocus/issues/3502 (more details)

**Closed by mashb1t** 2024-08-11 20:56 UTC
Labels: bug, triage
