### ISSUE TITLE
Regional prompter support. Again

### ISSUE THREAD

**Issue by ikqik** [lllyasviel/Fooocus#1669] opened 2023-12-30 19:48 UTC
Dear lllyasviel, please, think again about adding support for regional prompter. Or at least support for the token BREAK. I understand that fooocus has a unique inpaint engine, but regional prompter allow you to make a detailed description of the multiple characters.
![VT57JKOoXA28p6kTbRqVc](https://github.com/lllyasviel/Fooocus/assets/113307056/0b78605e-7f09-4075-8fd6-5beccede0199)

**Comment by mashb1t** [comment] 2023-12-30 23:01
Relates to / duplicate of https://github.com/lllyasviel/Fooocus/issues/1596 and  https://github.com/lllyasviel/Fooocus/issues/1391, specifically https://github.com/lllyasviel/Fooocus/issues/1391#issuecomment-1856256163.

@ikqik The multi-iterative approach with inpainting is working already. What's the benefit having this feature over having "only" inpainting when the proposal has already been declined?

**Comment by mashb1t** [comment] 2023-12-31 12:21
Getting emotional doesn't answer the question in the slightest. Closing this issue as duplicate.

**Closed by mashb1t** 2023-12-31 12:21 UTC
Labels: duplicate
