### ISSUE TITLE
History Log Management (Delete images and info)

### ISSUE THREAD

**Issue by EianAtDawn** [lllyasviel/Fooocus#2099] opened 2024-01-30 00:33 UTC
Please consider adding an option to be able to delete images from log..
I know they can be deleted from the output folder but the log file does not update accordingly.

**Comment by mashb1t** [comment] 2024-01-30 01:12
@EianAtDawn thank you for reporting. Closing as duplicate of https://github.com/lllyasviel/Fooocus/issues/1946

**Closed by mashb1t** 2024-01-30 01:12 UTC

**Comment by pablootero-cl** [comment] 2024-06-28 06:28
For the moment I can suggest creating a .ps1 powershell and placing it next to your Fooocus shortcut with the following line inside:
**Remove-Item "X:\Fooocus_mashb1t_win64_2-1-864\Fooocus_mashb1t_win64_2-1-864\Fooocus\outputs\*.*" -Confirm**

**Comment by pablootero-cl** [comment] 2024-06-28 06:29
Remove-Item "D:\Fooocus_mashb1t_win64_2-1-864\Fooocus_mashb1t_win64_2-1-864\Fooocus\outputs\*.*" -Confirm

sorry, I forgot a backslash in the previous comment

**Comment by pablootero-cl** [comment] 2024-07-07 07:32
You can also do a BASH. FooocusDELhistory.bat using a notepad.
just a few lines:
* Delete directory
* Create directory
* Open Directory
* Exit

`rmdir /s /q "D:\Fooocus_mashb1t_win64_2-1-864\Fooocus_mashb1t_win64_2-1-864\Fooocus\outputs\"`
`mkdir "D:\Fooocus_mashb1t_win64_2-1-864\Fooocus_mashb1t_win64_2-1-864\Fooocus\outputs\"`
`start explorer.exe "D:\Fooocus_mashb1t_win64_2-1-864\Fooocus_mashb1t_win64_2-1-864\Fooocus\outputs\"`
`exit`

# You can place the *.bat so that it runs at the start of Windows, so that it is automatically deleted every time you start the PC.
`C:\Users\YOUR_User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`
