### ISSUE TITLE
[Feature Request]: Plz add an option to export metadata for A1111/Forge/CivitAI 

### ISSUE THREAD

**Issue by Bra2ha** [lllyasviel/Fooocus#3443] opened 2024-08-03 21:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Please add an option to save metadata in a format so that the user could automatically import a file with such metadata into A1111/Forge/CivitAi without having to manually copy and merge parts of the metadata.

### Proposed workflow

Format example: 
**Style3beg, Style2beg, Style1beg, Main prompt, Style1end, Style2end, Style3end 
Negative prompt: Main negative prompt, NegStyle1, NegStyle2, NegStyle3
Settings**

**Comment by mashb1t** [comment] 2024-08-03 21:46
Duplicate of https://github.com/lllyasviel/Fooocus/issues/3425

The format of the metadata doesn't change the fact that the prompts used to create the image are in the format
style1beg, prompt, style1end
style2beg, prompt, style2end
...

Adjusting the code as you've suggested will in fact falsify the used prompt and you will be less able to reproduce the image.

**Closed by mashb1t** 2024-08-03 21:46 UTC
Labels: enhancement, triage
