### ISSUE TITLE
Feature Request: Metadata

### ISSUE THREAD

**Issue by blackpro98** [lllyasviel/Fooocus#86] opened 2023-08-14 22:23 UTC
Hi, I love the simple that is generate a image but I noticed that the images generated doesn't include the metadata in the image itself.

**Comment by p21nc3** [comment] 2023-08-15 05:47
Working on it 😊

**Comment by harrr1** [comment] 2023-08-15 11:39
Seems like a duplicate of #38

**Comment by KrX3D** [comment] 2023-08-15 12:58
it would also be nice after this is added to be able to load those information from an image

**Comment by lllyasviel** [comment] 2023-08-15 18:31
https://github.com/lllyasviel/Fooocus/issues/125

**Closed by lllyasviel** 2023-08-15 18:31 UTC
